package com.gotocompany.depot.maxcompute.schema.partition;

import com.aliyun.odps.Column;
import com.aliyun.odps.PartitionSpec;
import com.aliyun.odps.type.TypeInfo;
import com.gotocompany.depot.config.MaxComputeSinkConfig;
import lombok.RequiredArgsConstructor;

/**
 * Partitioning strategy for value-typed partition keys, where the partition key field itself becomes
 * the table's partition column.
 *
 * <p>This strategy is selected for non-timestamp partition keys (such as string or integer keys). The
 * original field is replaced by the partition column (see {@link #shouldReplaceOriginalColumn()}), and
 * the partition specification is formed directly from the field's value, falling back to a sentinel
 * value when the value is {@code null}. The all-arguments constructor is generated by Lombok.</p>
 *
 * @see PartitioningStrategy
 * @see TimestampPartitioningStrategy
 */
@RequiredArgsConstructor
public class DefaultPartitioningStrategy implements PartitioningStrategy {

    /**
     * Format string used to render a partition specification as {@code columnName=value}.
     */
    private static final String PARTITION_SPEC_FORMAT = "%s=%s";
    /**
     * Sentinel partition value used when the partition key value is {@code null}.
     */
    private static final String DEFAULT_PARTITION = "__NULL__";

    /**
     * MaxCompute type of the partition column, used when building the partition column definition.
     */
    private final TypeInfo typeInfo;
    /**
     * Sink configuration providing the partition key and partition column names.
     */
    private final MaxComputeSinkConfig maxComputeSinkConfig;

    /**
     * Get the original partition column name which is the key in the message payload.
     *
     * @return original partition column name
     */
    @Override
    public String getOriginalPartitionColumnName() {
        return maxComputeSinkConfig.getTablePartitionKey();
    }

    /**
     * Default partitioning strategy replaces the original column hence no additional column is added.
     *
     * @return true
     */
    @Override
    public boolean shouldReplaceOriginalColumn() {
        return true;
    }

    /**
     * Get the partition column.
     *
     * @return partition column
     */
    @Override
    public Column getPartitionColumn() {
        return Column.newBuilder(maxComputeSinkConfig.getTablePartitionColumnName(), typeInfo)
                .build();
    }

    /**
     * To get the partitionSpec with the format of partitionColumnName=partitionValue.
     *
     * <p>When the supplied value is {@code null}, the sentinel {@code __NULL__} partition value is used
     * in place of the value.</p>
     *
     * @param object the object for which the partition spec is to be generated
     * @return partition spec
     */
    @Override
    public PartitionSpec getPartitionSpec(Object object) {
        if (object == null) {
            return new PartitionSpec(String.format(PARTITION_SPEC_FORMAT, maxComputeSinkConfig.getTablePartitionColumnName(), DEFAULT_PARTITION));
        }
        return new PartitionSpec(String.format(PARTITION_SPEC_FORMAT, maxComputeSinkConfig.getTablePartitionColumnName(), object));
    }

}
