package com.gotocompany.depot.maxcompute.record;

import com.gotocompany.depot.config.MaxComputeSinkConfig;
import com.gotocompany.depot.config.SinkConfig;
import com.gotocompany.depot.maxcompute.converter.ProtobufConverterOrchestrator;
import com.gotocompany.depot.maxcompute.schema.MaxComputeSchemaCache;
import com.gotocompany.depot.maxcompute.schema.partition.PartitioningStrategy;
import com.gotocompany.depot.maxcompute.util.MetadataUtil;
import com.gotocompany.depot.message.MessageParser;
import com.gotocompany.depot.metrics.MaxComputeMetrics;
import com.gotocompany.depot.metrics.StatsDReporter;
import lombok.RequiredArgsConstructor;

/**
 * Factory that assembles the {@link RecordDecorator} chain used by the MaxCompute sink to turn Depot
 * messages into MaxCompute records.
 *
 * <p>The chain always contains a {@link ProtoDataColumnRecordDecorator} that maps Protobuf payload
 * fields to data (and partition) columns. When metadata columns are enabled in configuration, a
 * {@link ProtoMetadataColumnRecordDecorator} is wrapped around it so that metadata is appended after
 * the data columns are populated.</p>
 */
public class RecordDecoratorFactory {

    /**
     * Create a record decorator based on the sink configuration.
     * Creates a nested decorator in case of metadata column being enabled.
     *
     * @param recordDecoratorConfig record decorator configuration
     * @return record decorator
     */
    public static RecordDecorator createRecordDecorator(RecordDecoratorConfig recordDecoratorConfig) {
        RecordDecorator dataColumnRecordDecorator = new ProtoDataColumnRecordDecorator(null,
                recordDecoratorConfig.protobufConverterOrchestrator,
                recordDecoratorConfig.messageParser,
                recordDecoratorConfig.sinkConfig,
                recordDecoratorConfig.partitioningStrategy,
                recordDecoratorConfig.statsDReporter,
                recordDecoratorConfig.maxComputeMetrics);
        if (!recordDecoratorConfig.maxComputeSinkConfig.shouldAddMetadata()) {
            return dataColumnRecordDecorator;
        }
        return new ProtoMetadataColumnRecordDecorator(dataColumnRecordDecorator, recordDecoratorConfig.maxComputeSinkConfig,
                recordDecoratorConfig.maxComputeSchemaCache, recordDecoratorConfig.metadataUtil);
    }

    /**
     * Immutable parameter object that carries every collaborator and configuration value required to
     * build the record-decorator chain.
     *
     * <p>Grouping these dependencies into a single object keeps
     * {@link #createRecordDecorator(RecordDecoratorConfig)} to a single argument and makes the wiring
     * of the data-column and metadata-column decorators explicit. The all-arguments constructor is
     * generated by Lombok.</p>
     */
    @RequiredArgsConstructor
    public static class RecordDecoratorConfig {
        /**
         * Converts Protobuf fields to MaxCompute types and values; used by the data-column decorator.
         */
        private final ProtobufConverterOrchestrator protobufConverterOrchestrator;
        /**
         * Cache of the current MaxCompute schema, consulted by the metadata-column decorator to align
         * metadata values with the table's metadata columns.
         */
        private final MaxComputeSchemaCache maxComputeSchemaCache;
        /**
         * Parser used to decode the raw Depot message into a Protobuf message for the data-column
         * decorator.
         */
        private final MessageParser messageParser;
        /**
         * Strategy describing how the destination table is partitioned, used to derive each record's
         * partition specification.
         */
        private final PartitioningStrategy partitioningStrategy;
        /**
         * MaxCompute-specific sink configuration; in particular it determines whether metadata columns
         * are enabled.
         */
        private final MaxComputeSinkConfig maxComputeSinkConfig;
        /**
         * General sink configuration, such as the schema message mode and Protobuf schema classes.
         */
        private final SinkConfig sinkConfig;
        /**
         * Reporter used to emit StatsD metrics from the decorators.
         */
        private final StatsDReporter statsDReporter;
        /**
         * MaxCompute metric names and tags used when instrumenting the decoration pipeline.
         */
        private final MaxComputeMetrics maxComputeMetrics;
        /**
         * Helper that resolves metadata column types and coerces metadata values, used by the
         * metadata-column decorator.
         */
        private final MetadataUtil metadataUtil;
    }

}
