package com.gotocompany.depot.error;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Immutable detail record describing a single processing failure within a Depot sink.
 *
 * <p>An {@code ErrorInfo} pairs the {@link Exception} that caused a record to fail with an
 * {@link ErrorType} that classifies the failure. Instances are produced wherever a sink detects a
 * per-record problem — during parsing, schema validation, or while writing to the destination — and
 * are collected in a {@link com.gotocompany.depot.SinkResponse}, keyed by the failed message's index,
 * so callers can react to each failure according to its {@link ErrorType}.</p>
 *
 * <p>The all-arguments constructor generated by Lombok's {@code @AllArgsConstructor} accepts the
 * exception followed by the error type. Lombok's {@code @Data} supplies the accessors and the
 * value-based {@code equals} and {@code hashCode}; because the exception field is annotated
 * {@code @EqualsAndHashCode.Exclude}, equality depends solely on the {@link ErrorType}, so two
 * {@code ErrorInfo} values are equal when they share the same category regardless of the specific
 * exception instance.</p>
 *
 * @see ErrorType
 * @see com.gotocompany.depot.SinkResponse
 */
@AllArgsConstructor
@Data
public class ErrorInfo {

    /**
     * The throwable that caused the record to fail.
     *
     * <p>Excluded from {@code equals} and {@code hashCode} via {@code @EqualsAndHashCode.Exclude}, so
     * it does not participate in equality comparisons. May be {@code null}, which {@link #toString()}
     * renders as the literal {@code NULL}.</p>
     */
    @EqualsAndHashCode.Exclude
    private Exception exception;
    /**
     * The category that classifies this failure and drives downstream error handling.
     */
    private ErrorType errorType;

    /**
     * Returns a concise, human-readable description of this failure.
     *
     * <p>The text is produced with {@link String#format(String, Object...)} and consists of the word
     * {@code Exception} followed by the {@linkplain Exception#getMessage() message} of the wrapped
     * exception (or the literal {@code NULL} when the exception is {@code null}), then
     * {@code , ErrorType:} followed by the {@linkplain ErrorType#name() name} of the
     * {@link ErrorType}. This explicit implementation overrides the {@code toString} that Lombok's
     * {@code @Data} would otherwise generate.</p>
     *
     * @return a formatted summary pairing the exception message with the error type name
     */
    public String toString() {
        return String.format("Exception %s, ErrorType: %s", exception != null ? exception.getMessage() : "NULL", errorType.name());
    }
}
