package com.gotocompany.depot.bigtable.response;

import com.google.cloud.bigtable.data.v2.models.MutateRowsException;
import lombok.Getter;

import java.util.List;

/**
 * Captures the failed mutations from a partially failed Bigtable bulk write.
 *
 * <p>When a bulk mutation does not fully succeed the Bigtable client raises a
 * {@link com.google.cloud.bigtable.data.v2.models.MutateRowsException}; {@code BigTableResponse}
 * extracts its list of
 * {@link com.google.cloud.bigtable.data.v2.models.MutateRowsException.FailedMutation} so the sink can
 * report and classify the failures. The accessor for that list is generated by Lombok's
 * {@code @Getter}. A response is only created when there is at least one failure.</p>
 *
 * @see com.gotocompany.depot.bigtable.client.BigTableClient
 * @see com.gotocompany.depot.bigtable.parser.BigTableResponseParser
 */
@Getter
public class BigTableResponse {
    /** The mutations that failed to be applied, taken from the originating exception. */
    private final List<MutateRowsException.FailedMutation> failedMutations;

    /**
     * Creates a response from the exception thrown by a partially failed bulk mutation.
     *
     * @param e the exception whose
     *     {@link com.google.cloud.bigtable.data.v2.models.MutateRowsException#getFailedMutations()}
     *     supply this response's failed mutations
     */
    public BigTableResponse(MutateRowsException e) {
        failedMutations = e.getFailedMutations();
    }

    /**
     * Reports whether any mutation failed.
     *
     * @return {@code true} if there is at least one failed mutation, {@code false} otherwise
     */
    public boolean hasErrors() {
        return !failedMutations.isEmpty();
    }

    /**
     * Returns the number of failed mutations.
     *
     * @return the count of mutations that failed to be applied
     */
    public int getErrorCount() {
        return failedMutations.size();
    }
}
