package com.gotocompany.depot.bigquery.converter;

import lombok.Data;

/**
 * Mutable holder that caches the active {@link MessageRecordConverter} instance.
 *
 * <p>The converter depends on the parsed schema, which can change at runtime. Rather than recreating
 * the converter everywhere it is needed, the sink stores a single converter in this cache and swaps it
 * out when the schema is refreshed; collaborators read the current converter from the cache at use
 * time. This indirection lets schema updates take effect without rewiring dependents.</p>
 *
 * <p>The {@code getMessageRecordConverter()} accessor and {@code setMessageRecordConverter(...)}
 * mutator are generated by Lombok via {@link Data}.</p>
 *
 * @see MessageRecordConverter
 */
@Data
public class MessageRecordConverterCache {
    /** The currently active converter, replaced whenever the schema is refreshed. */
    private MessageRecordConverter messageRecordConverter;
}
