package com.gotocompany.depot.bigquery.converter;

import com.google.api.client.util.DateTime;
import com.google.api.client.util.Preconditions;
import com.google.common.io.BaseEncoding;
import com.google.protobuf.ByteString;
import com.gotocompany.depot.bigquery.models.Record;
import com.gotocompany.depot.bigquery.models.Records;
import com.gotocompany.depot.config.BigQuerySinkConfig;
import com.gotocompany.depot.error.ErrorInfo;
import com.gotocompany.depot.error.ErrorType;
import com.gotocompany.depot.exception.DeserializerException;
import com.gotocompany.depot.exception.EmptyMessageException;
import com.gotocompany.depot.exception.UnknownFieldsException;
import com.gotocompany.depot.message.Message;
import com.gotocompany.depot.message.MessageParser;
import com.gotocompany.depot.message.ParsedMessage;
import com.gotocompany.depot.message.ProtoUnknownFieldValidationType;
import com.gotocompany.depot.message.SinkConnectorSchemaMessageMode;
import com.gotocompany.depot.schema.LogicalType;
import com.gotocompany.depot.schema.SchemaField;
import com.gotocompany.depot.schema.SchemaFieldType;
import lombok.extern.slf4j.Slf4j;
import org.json.JSONObject;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Converts incoming {@link Message} objects into BigQuery {@link Record}s for the legacy
 * {@code insertAll} sink path.
 *
 * <p>For each message this converter parses the payload against the configured schema, optionally
 * validates unknown Protobuf fields, maps the parsed fields into a BigQuery-compatible column map and
 * appends metadata and (for JSON) an event-timestamp column. The result is partitioned into valid and
 * invalid records: a conversion failure does not abort the batch but instead produces an invalid
 * {@link Record} carrying a classified {@link ErrorInfo}, so the caller can route good rows to
 * BigQuery and failed rows to error handling.</p>
 *
 * <p>Field mapping handles the type-specific transformations BigQuery requires, including rejecting
 * non-finite floating-point values, base64-encoding byte fields, converting timestamp logical types to
 * {@link com.google.api.client.util.DateTime}, serializing struct logical types to JSON strings,
 * recursing into nested messages and mapping repeated fields element-wise.</p>
 *
 * <p>The {@code log} field is generated by Lombok via {@link lombok.extern.slf4j.Slf4j}.</p>
 *
 * @see MessageRecordConverterUtils
 * @see Records
 */
@Slf4j
public class MessageRecordConverter {

    /** Parser used to deserialize messages into {@link ParsedMessage} instances. */
    private final MessageParser parser;
    /** Sink configuration providing schema classes, modes and validation toggles. */
    private final BigQuerySinkConfig config;
    /** Strategy controlling how unknown Protobuf fields are validated. */
    private final ProtoUnknownFieldValidationType unknownFieldValidationType;
    /** Whether unknown Protobuf fields are permitted (when {@code true}, validation is skipped). */
    private final boolean sinkConnectorSchemaProtoAllowUnknownFieldsEnable;

    /**
     * Creates a converter bound to a parser and configuration.
     *
     * <p>The unknown-field validation strategy and the allow-unknown-fields toggle are captured from
     * the configuration at construction time.</p>
     *
     * @param parser the message parser used for deserialization
     * @param config the BigQuery sink configuration
     */
    public MessageRecordConverter(MessageParser parser, BigQuerySinkConfig config) {
        this.parser = parser;
        this.config = config;
        this.unknownFieldValidationType = config.getSinkConnectorSchemaProtoUnknownFieldsValidation();
        this.sinkConnectorSchemaProtoAllowUnknownFieldsEnable = config.getSinkConnectorSchemaProtoAllowUnknownFieldsEnable();
    }

    /**
     * Converts a batch of messages into valid and invalid {@link Record}s.
     *
     * <p>Each message is converted in input order. Successful conversions are collected as valid
     * records; failures are caught and classified into an invalid record (preserving the message
     * metadata, the original index and an {@link ErrorInfo}) according to the exception type:</p>
     * <ul>
     *     <li>{@link UnknownFieldsException} maps to {@link ErrorType#UNKNOWN_FIELDS_ERROR}.</li>
     *     <li>{@link EmptyMessageException} and {@link UnsupportedOperationException} map to
     *     {@link ErrorType#INVALID_MESSAGE_ERROR}.</li>
     *     <li>{@link DeserializerException} and {@link IllegalArgumentException} map to
     *     {@link ErrorType#DESERIALIZATION_ERROR}.</li>
     * </ul>
     *
     * @param messages the ordered batch of messages to convert
     * @return a {@link Records} bundle holding the valid and invalid records
     */
    public Records convert(List<Message> messages) {
        ArrayList<Record> validRecords = new ArrayList<>();
        ArrayList<Record> invalidRecords = new ArrayList<>();
        for (int index = 0; index < messages.size(); index++) {
            Message message = messages.get(index);
            try {
                Record record = createRecord(message, index);
                validRecords.add(record);
            } catch (UnknownFieldsException e) {
                ErrorInfo errorInfo = new ErrorInfo(e, ErrorType.UNKNOWN_FIELDS_ERROR);
                invalidRecords.add(new Record(message.getMetadata(), Collections.emptyMap(), index, errorInfo));
            } catch (EmptyMessageException | UnsupportedOperationException e) {
                ErrorInfo errorInfo = new ErrorInfo(e, ErrorType.INVALID_MESSAGE_ERROR);
                invalidRecords.add(new Record(message.getMetadata(), Collections.emptyMap(), index, errorInfo));
            } catch (DeserializerException | IllegalArgumentException e) {
                ErrorInfo errorInfo = new ErrorInfo(e, ErrorType.DESERIALIZATION_ERROR);
                invalidRecords.add(new Record(message.getMetadata(), Collections.emptyMap(), index, errorInfo));
            }
        }
        return new Records(validRecords, invalidRecords);
    }

    /**
     * Parses and converts a single message into a valid {@link Record}.
     *
     * <p>Resolves the schema class from the configured message mode (the message class for
     * {@code LOG_MESSAGE}, otherwise the key class), parses the message, optionally validates unknown
     * fields, maps the parsed fields to a column map and enriches it with metadata and (for JSON) the
     * event timestamp before assembling the record.</p>
     *
     * @param message the message to convert
     * @param index   the zero-based position of the message within the input batch
     * @return the converted record with a {@code null} error info
     * @throws DeserializerException     if the message fails to deserialize (wrapping the underlying
     *                                   {@link IOException})
     * @throws UnknownFieldsException    if unknown-field validation rejects the message
     * @throws EmptyMessageException     if the message is empty
     * @throws IllegalArgumentException  if a field value is invalid (for example a non-finite float)
     * @throws UnsupportedOperationException if a value is not supported for conversion
     */
    private Record createRecord(Message message, int index) {
        try {
            SinkConnectorSchemaMessageMode mode = config.getSinkConnectorSchemaMessageMode();
            String schemaClass = mode == SinkConnectorSchemaMessageMode.LOG_MESSAGE
                    ? config.getSinkConnectorSchemaProtoMessageClass() : config.getSinkConnectorSchemaProtoKeyClass();
            ParsedMessage parsedMessage = parser.parse(message, mode, schemaClass);
            if (!sinkConnectorSchemaProtoAllowUnknownFieldsEnable) {
                parsedMessage.validate(unknownFieldValidationType);
            }
            Map<String, Object> columns = getMapping(parsedMessage);
            MessageRecordConverterUtils.addMetadata(columns, message, config);
            MessageRecordConverterUtils.addTimeStampColumnForJson(columns, config);
            return new Record(message.getMetadata(), columns, index, null);
        } catch (IOException e) {
            log.error("failed to deserialize message: {}, {} ", e, message.getMetadataString());
            throw new DeserializerException("failed to deserialize ", e);
        }
    }

    /**
     * Validates that a floating-point value is finite (neither infinite nor NaN).
     *
     * <p>BigQuery does not accept infinite or NaN numeric values, so such values are rejected here.
     * Non floating-point values are ignored.</p>
     *
     * @param fieldValue the value to check; only {@link Float} and {@link Double} are validated
     * @throws IllegalArgumentException if the value is an infinite or NaN {@code Float} or {@code Double}
     */
    private void floatCheck(Object fieldValue) {
        if (fieldValue instanceof Float) {
            float floatValue = ((Number) fieldValue).floatValue();
            Preconditions.checkArgument(!Float.isInfinite(floatValue) && !Float.isNaN(floatValue));
        } else if (fieldValue instanceof Double) {
            double doubleValue = ((Number) fieldValue).doubleValue();
            Preconditions.checkArgument(!Double.isInfinite(doubleValue) && !Double.isNaN(doubleValue));
        }
    }

    /**
     * Converts a single (non-repeated) field value into its BigQuery-compatible representation.
     *
     * <p>The transformation depends on the field's {@link SchemaFieldType}:</p>
     * <ul>
     *     <li>{@code FLOAT}/{@code DOUBLE} values are validated for finiteness via
     *     {@link #floatCheck(Object)}.</li>
     *     <li>{@code BYTES} values are base64-encoded into a string.</li>
     *     <li>{@code MESSAGE} values are inspected by logical type: timestamps become
     *     {@link com.google.api.client.util.DateTime}, structs become a JSON string, and any other
     *     message is mapped recursively into a nested column map via {@link #getMapping(ParsedMessage)}.</li>
     *     <li>All other values are returned unchanged.</li>
     * </ul>
     *
     * @param field the schema field describing the value's type
     * @param value the raw value to convert
     * @return the converted, BigQuery-compatible value
     * @throws IllegalArgumentException if a floating-point value is infinite or NaN
     */
    private Object getFieldValue(SchemaField field, Object value) {
        if (field.getType().equals(SchemaFieldType.FLOAT) || field.getType().equals(SchemaFieldType.DOUBLE)) {
            floatCheck(value);
        }
        if (field.getType().equals(SchemaFieldType.BYTES)) {
            return BaseEncoding.base64().encode(((ByteString) value).toByteArray());
        }
        if (field.getType().equals(SchemaFieldType.MESSAGE)) {
            ParsedMessage msg = (ParsedMessage) value;
            if (msg.getSchema().logicalType().equals(LogicalType.TIMESTAMP)) {
                return new DateTime(msg.getLogicalValue().getTimestamp().toEpochMilli());
            }
            if (msg.getSchema().logicalType().equals(LogicalType.STRUCT)) {
                JSONObject json = new JSONObject(msg.getLogicalValue().getStruct());
                return json.toString();
            }
            return getMapping(msg);
        }
        return value;
    }

    /**
     * Converts each element of a repeated field into its BigQuery-compatible representation.
     *
     * @param schemaField the schema field describing the element type
     * @param value       the list of raw element values to convert
     * @return a list of converted values, one per input element
     * @throws IllegalArgumentException if any floating-point element is infinite or NaN
     */
    private Object getListValue(SchemaField schemaField, List<?> value) {
        return value
                .stream()
                .map(eachValue -> getFieldValue(schemaField, eachValue))
                .collect(Collectors.toList());
    }

    /**
     * Converts a single schema-field entry, dispatching to repeated or scalar handling.
     *
     * @param kv the field-to-value entry to convert
     * @return the converted value: a list for repeated fields, otherwise the scalar conversion
     * @throws IllegalArgumentException if a floating-point value is infinite or NaN
     */
    private Object getValue(Map.Entry<SchemaField, Object> kv) {
        SchemaField schemaField = kv.getKey();
        Object value = kv.getValue();
        if (schemaField.isRepeated()) {
            return getListValue(schemaField, (List<?>) value);
        }
        return getFieldValue(schemaField, value);
    }

    /**
     * Maps all fields of a parsed message into a column map keyed by field name.
     *
     * <p>Each present field is converted via {@link #getValue(Map.Entry)} and collected into a map from
     * the field's name to its BigQuery-compatible value. This method is also invoked recursively for
     * nested message fields.</p>
     *
     * @param msg the parsed message whose fields are mapped
     * @return a map from field name to converted column value
     * @throws IllegalArgumentException if a floating-point value is infinite or NaN
     */
    private Map<String, Object> getMapping(ParsedMessage msg) {
        return msg
                .getFields()
                .entrySet()
                .stream()
                .collect(Collectors.toMap(kv -> kv.getKey().getName(), this::getValue));
    }
}
