package com.gotocompany.depot.bigtable.model;

import com.google.cloud.bigtable.data.v2.models.RowMutationEntry;
import com.gotocompany.depot.error.ErrorInfo;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Map;

/**
 * Immutable result of converting one consumed message into a Bigtable mutation, or into an error when
 * conversion failed.
 *
 * <p>A {@code BigTableRecord} carries either a ready-to-apply
 * {@link com.google.cloud.bigtable.data.v2.models.RowMutationEntry} (a valid record) or an
 * {@link ErrorInfo} describing why the message could not be converted (an invalid record), together
 * with the originating message {@code index} and the message {@code metadata}. The sink partitions
 * records on {@link #isValid()}: valid records are sent to Bigtable, while invalid ones are reported
 * directly as failures.</p>
 *
 * <p>The all-arguments constructor and the accessors are generated by Lombok's
 * {@code @AllArgsConstructor} and {@code @Getter}.</p>
 *
 * @see com.gotocompany.depot.bigtable.parser.BigTableRecordParser
 */
@AllArgsConstructor
@Getter
public class BigTableRecord {
    /** Row mutation to apply to Bigtable, or {@code null} when this record represents a failure. */
    private final RowMutationEntry rowMutationEntry;
    /** Zero-based index of the originating message within the submitted batch. */
    private final long index;
    /** Failure detail when conversion failed, or {@code null} for a valid record. */
    private final ErrorInfo errorInfo;
    /** Metadata copied from the originating message, used when reporting errors. */
    private final Map<String, Object> metadata;

    /**
     * Reports whether this record converted successfully and is safe to write.
     *
     * @return {@code true} if no {@link ErrorInfo} is attached (the record holds a mutation),
     *     {@code false} if the record represents a conversion failure
     */
    public boolean isValid() {
        return errorInfo == null;
    }
}
