package com.gotocompany.depot.bigquery.storage.proto;

import com.google.api.core.ApiFuture;
import com.google.api.gax.core.CredentialsProvider;
import com.google.cloud.bigquery.storage.v1.AppendRowsResponse;
import com.google.cloud.bigquery.storage.v1.BQTableSchemaToProtoDescriptor;
import com.google.cloud.bigquery.storage.v1.BigQueryWriteClient;
import com.google.cloud.bigquery.storage.v1.GetWriteStreamRequest;
import com.google.cloud.bigquery.storage.v1.ProtoRows;
import com.google.cloud.bigquery.storage.v1.ProtoSchema;
import com.google.cloud.bigquery.storage.v1.ProtoSchemaConverter;
import com.google.cloud.bigquery.storage.v1.StreamWriter;
import com.google.cloud.bigquery.storage.v1.TableSchema;
import com.google.cloud.bigquery.storage.v1.WriteStream;
import com.google.cloud.bigquery.storage.v1.WriteStreamView;
import com.google.protobuf.Descriptors;
import com.gotocompany.depot.bigquery.storage.BigQueryPayload;
import com.gotocompany.depot.bigquery.storage.BigQueryStorageResponseParser;
import com.gotocompany.depot.bigquery.storage.BigQueryStream;
import com.gotocompany.depot.bigquery.storage.BigQueryWriter;
import com.gotocompany.depot.bigquery.storage.BigQueryWriterUtils;
import com.gotocompany.depot.common.Function3;
import com.gotocompany.depot.config.BigQuerySinkConfig;
import com.gotocompany.depot.metrics.BigQueryMetrics;
import com.gotocompany.depot.metrics.Instrumentation;
import lombok.Getter;

import java.io.IOException;
import java.time.Instant;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;

/**
 * {@link BigQueryWriter} implementation that streams Protobuf rows through the BigQuery Storage Write
 * API.
 *
 * <p>The writer manages the lifecycle of a {@code StreamWriter} bound to the table's default stream
 * and the Protobuf descriptor/schema derived from the live BigQuery table schema. Its responsibilities
 * include:</p>
 * <ul>
 *     <li>Fetching the destination table schema and building the matching Protobuf descriptor and
 *     {@code ProtoSchema} during {@link #init()}.</li>
 *     <li>Appending serialized {@code ProtoRows} and returning the server response via
 *     {@link #appendAndGet(BigQueryPayload)}.</li>
 *     <li>Detecting and recovering from stale, closed or schema-changed streams through
 *     {@link #checkAndRefreshConnection()}.</li>
 *     <li>Emitting operation counters, latency and payload-size metrics for each Storage Write API
 *     interaction.</li>
 * </ul>
 *
 * <p>The heavy collaborators (write client, credentials provider and stream) are supplied as creator
 * functions, which keeps the class testable and lets it recreate the stream on demand. A connection
 * that has been idle for longer than {@value #INTERNAL_CONNECTION_TIMEOUT} minutes is treated as
 * inactive and recreated. Methods that mutate or recreate the stream synchronize on the instance, as
 * {@link #checkAndRefreshConnection()} may be invoked from a different thread than the append path.</p>
 *
 * <p>The {@code getStreamWriter()} and {@code getDescriptor()} accessors are generated by Lombok via
 * {@link Getter}.</p>
 *
 * @see com.gotocompany.depot.bigquery.storage.BigQueryWriterUtils
 * @see BigQueryProtoStorageClient
 */
public class BigQueryProtoWriter implements BigQueryWriter {

    /** Idle timeout, in minutes, after which an unused stream connection is considered inactive and recreated. */
    private static final int INTERNAL_CONNECTION_TIMEOUT = 10;
    /** Sink configuration providing project/dataset/table identifiers and behavioural toggles. */
    private final BigQuerySinkConfig config;
    /** Factory that creates a {@code BigQueryWriteClient} used to fetch the table schema. */
    private final Function<BigQuerySinkConfig, BigQueryWriteClient> bqWriterCreator;
    /** Factory that creates the {@code CredentialsProvider} authenticating the stream. */
    private final Function<BigQuerySinkConfig, CredentialsProvider> credCreator;
    /** Factory that creates a {@link BigQueryStream} from the config, credentials and schema. */
    private final Function3<BigQuerySinkConfig, CredentialsProvider, ProtoSchema, BigQueryStream> streamCreator;
    /** Instrumentation used for logging and metric emission. */
    private final Instrumentation instrumentation;
    /** Provider of BigQuery metric names and tag templates. */
    private final BigQueryMetrics metrics;
    /** The active Storage Write API stream writer; recreated when stale, closed or on schema change. */
    @Getter
    private StreamWriter streamWriter;
    /** The Protobuf descriptor matching the current BigQuery table schema. */
    @Getter
    private Descriptors.Descriptor descriptor;
    /** The Protobuf schema (derived from {@link #descriptor}) configured on the stream writer. */
    private ProtoSchema schema;
    /** Whether the writer has been permanently closed and can no longer accept appends. */
    private boolean isClosed = false;
    /** {@link System#nanoTime()} of the most recent stream creation or append, used for idle detection. */
    private long lastAppendTimeStamp;

    /**
     * Creates a Protobuf writer with the collaborators it needs to build and refresh its stream.
     *
     * <p>The constructor only stores its dependencies; the actual connection and schema are
     * established later by {@link #init()}.</p>
     *
     * @param config          the BigQuery sink configuration
     * @param bqWriterCreator factory that creates a {@code BigQueryWriteClient} from the configuration
     * @param credCreator     factory that creates a {@code CredentialsProvider} from the configuration
     * @param streamCreator   factory that creates a {@link BigQueryStream} from the configuration,
     *                        credentials provider and Protobuf schema
     * @param instrumentation the instrumentation used for logging and metric emission
     * @param metrics         the provider of BigQuery metric names and tags
     */
    public BigQueryProtoWriter(BigQuerySinkConfig config,
                               Function<BigQuerySinkConfig, BigQueryWriteClient> bqWriterCreator,
                               Function<BigQuerySinkConfig, CredentialsProvider> credCreator,
                               Function3<BigQuerySinkConfig, CredentialsProvider, ProtoSchema, BigQueryStream> streamCreator,
                               Instrumentation instrumentation, BigQueryMetrics metrics) {
        this.config = config;
        this.bqWriterCreator = bqWriterCreator;
        this.credCreator = credCreator;
        this.streamCreator = streamCreator;
        this.instrumentation = instrumentation;
        this.metrics = metrics;
    }

    /**
     * Establishes the Storage Write API connection using the schema fetched from BigQuery.
     *
     * <p>Requests the full {@code WriteStream} for the table's default stream, reads its table schema
     * and uses it to build the Protobuf descriptor, {@code ProtoSchema} and {@code StreamWriter}. The
     * temporary write client used to fetch the schema is closed automatically once the writer is
     * created.</p>
     *
     * @throws IllegalArgumentException if the table schema cannot be converted into a valid Protobuf
     *                                  descriptor (wrapping a
     *                                  {@code Descriptors.DescriptorValidationException})
     */
    @Override
    public void init() {
        // Creates the connection with schema fetched from the server.
        try {
            String streamName = BigQueryWriterUtils.getDefaultStreamName(config);
            GetWriteStreamRequest writeStreamRequest =
                    GetWriteStreamRequest.newBuilder()
                            .setName(streamName)
                            .setView(WriteStreamView.FULL)
                            .build();
            try (BigQueryWriteClient bigQueryInstance = bqWriterCreator.apply(config)) {
                WriteStream writeStream = bigQueryInstance.getWriteStream(writeStreamRequest);
                createAndSetStreamWriter(writeStream.getTableSchema());
            }
        } catch (Descriptors.DescriptorValidationException e) {
            throw new IllegalArgumentException("Could not initialise the bigquery writer", e);
        }
    }

    /**
     * Rebuilds the Protobuf descriptor, schema and stream writer from the given table schema.
     *
     * <p>Converts the BigQuery {@code TableSchema} into a Protobuf descriptor, derives the
     * {@code ProtoSchema} from it and creates a fresh stream writer bound to that schema. Used both
     * during initial setup and when a schema change is detected.</p>
     *
     * @param updatedSchema the table schema to base the descriptor and stream writer on
     * @throws Descriptors.DescriptorValidationException if the table schema cannot be converted into a
     *                                                   valid Protobuf descriptor
     */
    private void createAndSetStreamWriter(TableSchema updatedSchema) throws Descriptors.DescriptorValidationException {
        descriptor = BQTableSchemaToProtoDescriptor.convertBQTableSchemaToProtoDescriptor(updatedSchema);
        schema = ProtoSchemaConverter.convert(descriptor);
        streamWriter = createStreamWriter();
    }

    /**
     * Permanently closes the writer and its underlying stream.
     *
     * <p>Marks the writer as closed so subsequent appends are rejected, closes the active
     * {@code StreamWriter} and records the close operation's latency and counter metrics. The method
     * synchronizes on the instance to avoid racing with concurrent connection refreshes.</p>
     *
     * @throws IOException if closing the underlying stream writer fails
     */
    @Override
    public void close() throws IOException {
        synchronized (this) {
            isClosed = true;
            instrumentation.logInfo("Closing StreamWriter");
            Instant start = Instant.now();
            streamWriter.close();
            instrument(start, BigQueryMetrics.BigQueryStorageAPIType.STREAM_WRITER_CLOSED);
        }
    }

    /**
     * Appends the serialized rows to the stream and blocks until BigQuery responds.
     *
     * <p>If the writer has already been closed, a synthetic {@code FAILED_PRECONDITION} response is
     * returned (via {@link com.gotocompany.depot.bigquery.storage.BigQueryStorageResponseParser#get4xxErrorResponse()})
     * instead of attempting an append. Otherwise the payload's {@code ProtoRows} are appended through
     * the stream writer, the append future is awaited, and operation and payload-size metrics are
     * recorded. The last-append timestamp is updated so the idle-connection detector treats the stream
     * as recently active.</p>
     *
     * @param rows the payload whose serialized {@code ProtoRows} are appended
     * @return the {@code AppendRowsResponse} from BigQuery, or a synthetic error response if the
     *         writer is closed
     * @throws ExecutionException   if the append future completes exceptionally
     * @throws InterruptedException if the current thread is interrupted while awaiting the response
     */
    @Override
    public AppendRowsResponse appendAndGet(BigQueryPayload rows) throws ExecutionException, InterruptedException {
        if (isClosed) {
            instrumentation.logError("The client is permanently closed. More tasks can not be added");
            return BigQueryStorageResponseParser.get4xxErrorResponse();
        }
        ProtoRows payload = (ProtoRows) rows.getPayload();
        Instant start;
        start = Instant.now();
        lastAppendTimeStamp = System.nanoTime();
        ApiFuture<AppendRowsResponse> future = streamWriter.append(payload);
        AppendRowsResponse appendRowsResponse = future.get();
        instrument(start, BigQueryMetrics.BigQueryStorageAPIType.STREAM_WRITER_APPEND);
        captureSizeMetric(payload);
        return appendRowsResponse;
    }

    /**
     * Ensures the stream writer is healthy and up to date before the next batch is appended.
     *
     * <p>Invoked from the conversion path (potentially on a different thread than appends), so the
     * whole check synchronizes on the instance. The method reacts to three situations:</p>
     * <ul>
     *     <li>If there is no stream writer, the stream writer is closed, or the connection has been
     *     idle past the inactivity timeout, the stale stream is closed and the connection is fully
     *     re-initialised via {@link #init()}.</li>
     *     <li>If BigQuery reports an updated table schema, the current stream is closed and recreated
     *     against the new schema via {@link #createAndSetStreamWriter(TableSchema)}.</li>
     *     <li>Otherwise the existing stream is left untouched.</li>
     * </ul>
     *
     * @throws IllegalArgumentException if recreating the writer after a schema change fails because the
     *                                  updated schema cannot be converted to a valid Protobuf
     *                                  descriptor
     */
    public void checkAndRefreshConnection() {
        // Synchronize this because it's being called from outside
        synchronized (this) {
            if (streamWriter == null || streamWriter.isClosed() || checkInactiveConnection()) {
                instrumentation.logInfo("Recreating stream writer, because it was closed with exception or abandoned by the server");
                closeStreamWriter();
                init();
            } else {
                TableSchema updatedSchema = streamWriter.getUpdatedSchema();
                if (updatedSchema != null) {
                    instrumentation.logInfo("Updated table schema detected, recreating stream writer");
                    try {
                        closeStreamWriter();
                        createAndSetStreamWriter(updatedSchema);
                    } catch (Descriptors.DescriptorValidationException e) {
                        throw new IllegalArgumentException("Could not initialise the bigquery writer", e);
                    }
                }
            }
        }
    }

    /**
     * Closes the current stream writer if one exists and records the close metric.
     *
     * <p>Unlike {@link #close()} this does not mark the writer as permanently closed; it is used when
     * recreating the stream during a refresh.</p>
     */
    private void closeStreamWriter() {
        if (streamWriter != null) {
            Instant start = Instant.now();
            streamWriter.close();
            instrument(start, BigQueryMetrics.BigQueryStorageAPIType.STREAM_WRITER_CLOSED);
        }
    }

    /**
     * Determines whether the connection has been idle longer than the configured inactivity timeout.
     *
     * @return {@code true} if the time elapsed since the last stream creation or append meets or
     *         exceeds {@value #INTERNAL_CONNECTION_TIMEOUT} minutes, {@code false} otherwise
     */
    private boolean checkInactiveConnection() {
        return System.nanoTime() - lastAppendTimeStamp >= TimeUnit.MINUTES.toNanos(INTERNAL_CONNECTION_TIMEOUT);
    }

    /**
     * Creates a new {@code StreamWriter} for the current schema via the injected stream-creator
     * function.
     *
     * <p>Resets the last-append timestamp, logs the schema being used and records the stream-created
     * metric. The created {@link BigQueryStream} is asserted to be a {@link BigQueryProtoStream}, from
     * which the wrapped {@code StreamWriter} is returned.</p>
     *
     * @return the newly created Storage Write API stream writer
     */
    private StreamWriter createStreamWriter() {
        Instant start = Instant.now();
        lastAppendTimeStamp = System.nanoTime();
        BigQueryStream bigQueryStream =
                streamCreator.apply(
                        config,
                        credCreator.apply(config),
                        schema);
        instrumentation.logInfo("Creating bq write stream with schema {}", schema);
        instrument(start, BigQueryMetrics.BigQueryStorageAPIType.STREAM_WRITER_CREATED);
        assert (bigQueryStream instanceof BigQueryProtoStream);
        return ((BigQueryProtoStream) bigQueryStream).getStreamWriter();
    }

    /**
     * Records the serialized size, in bytes, of an appended payload as a count metric.
     *
     * @param payload the {@code ProtoRows} that were appended, whose serialized size is captured
     */
    private void captureSizeMetric(ProtoRows payload) {
        instrumentation.captureCount(
                metrics.getBigqueryPayloadSizeMetrics(),
                (long) payload.getSerializedSize(),
                String.format(BigQueryMetrics.BIGQUERY_TABLE_TAG, config.getTableName()),
                String.format(BigQueryMetrics.BIGQUERY_DATASET_TAG, config.getDatasetName()),
                String.format(BigQueryMetrics.BIGQUERY_PROJECT_TAG, config.getGCloudProjectID()));
    }

    /**
     * Emits the operation counter and latency metrics for a Storage Write API operation.
     *
     * <p>Increments the operation-total counter and captures the duration since {@code start}, both
     * tagged with the table, dataset, project and the supplied API type.</p>
     *
     * @param start the instant the operation began, used to compute its latency
     * @param type  the Storage Write API operation type used as the metric's API tag
     */
    private void instrument(Instant start, BigQueryMetrics.BigQueryStorageAPIType type) {
        instrumentation.incrementCounter(
                metrics.getBigqueryOperationTotalMetric(),
                String.format(BigQueryMetrics.BIGQUERY_TABLE_TAG, config.getTableName()),
                String.format(BigQueryMetrics.BIGQUERY_DATASET_TAG, config.getDatasetName()),
                String.format(BigQueryMetrics.BIGQUERY_PROJECT_TAG, config.getGCloudProjectID()),
                String.format(BigQueryMetrics.BIGQUERY_API_TAG, type));
        instrumentation.captureDurationSince(
                metrics.getBigqueryOperationLatencyMetric(),
                start,
                String.format(BigQueryMetrics.BIGQUERY_TABLE_TAG, config.getTableName()),
                String.format(BigQueryMetrics.BIGQUERY_DATASET_TAG, config.getDatasetName()),
                String.format(BigQueryMetrics.BIGQUERY_PROJECT_TAG, config.getGCloudProjectID()),
                String.format(BigQueryMetrics.BIGQUERY_API_TAG, type));
    }


}
