package com.gotocompany.depot.bigquery.storage.proto;

import com.google.cloud.bigquery.storage.v1.StreamWriter;
import com.gotocompany.depot.bigquery.storage.BigQueryStream;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * {@link BigQueryStream} implementation backing the Protobuf streaming path.
 *
 * <p>This is a thin immutable wrapper around a BigQuery Storage Write API {@code StreamWriter}. It
 * lets the Protobuf writer pass a stream around as the format-agnostic {@link BigQueryStream} type and
 * later recover the concrete {@code StreamWriter} for appending serialized {@code ProtoRows}.</p>
 *
 * <p>The all-arguments constructor and the {@code getStreamWriter()} accessor are generated by Lombok
 * via {@link AllArgsConstructor} and {@link Getter} respectively.</p>
 *
 * @see com.gotocompany.depot.bigquery.storage.BigQueryWriterUtils#getStreamWriter(
 *      com.gotocompany.depot.config.BigQuerySinkConfig,
 *      com.google.api.gax.core.CredentialsProvider, com.google.cloud.bigquery.storage.v1.ProtoSchema)
 */
@AllArgsConstructor
public class BigQueryProtoStream implements BigQueryStream {
    /** The wrapped Storage Write API stream writer used to append Protobuf rows. */
    @Getter
    private final StreamWriter streamWriter;
}
