package com.gotocompany.depot.bigquery.storage.proto;

import com.gotocompany.depot.error.ErrorInfo;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Immutable per-record metadata captured while converting a single message for the Storage Write API.
 *
 * <p>Exactly one instance is produced for every input message in a batch and stored in the
 * {@link com.gotocompany.depot.bigquery.storage.BigQueryPayload}. It records whether the message
 * converted successfully and, if not, the associated {@link ErrorInfo}, while always retaining the
 * message's position in the original input batch so failures can be reported against the correct
 * message.</p>
 *
 * <p>The all-arguments constructor and the {@code getInputIndex()}, {@code getErrorInfo()} and
 * {@code isValid()} accessors are generated by Lombok via {@link AllArgsConstructor} and
 * {@link Getter}.</p>
 *
 * @see com.gotocompany.depot.bigquery.storage.BigQueryPayload
 */
@AllArgsConstructor
@Getter
public class BigQueryRecordMeta {
    /** Zero-based index of the message within the original input batch. */
    private final long inputIndex;
    /** Conversion error for an invalid record, or {@code null} when the record is valid. */
    private final ErrorInfo errorInfo;
    /** {@code true} if the message converted successfully, {@code false} if it failed conversion. */
    private final boolean isValid;
}
