package com.gotocompany.depot.message.proto.converter.fields;


import com.google.protobuf.ByteString;
import com.google.protobuf.Descriptors;
import lombok.AllArgsConstructor;

import java.util.Base64;
import java.util.Collection;
import java.util.stream.Collectors;

/**
 * {@link ProtoField} strategy that converts Protobuf {@code BYTES} fields into base64-encoded strings.
 *
 * <p>The underlying {@link ByteString} value is decoded as UTF-8 text, the resulting string's bytes
 * are taken and then base64-encoded. Repeated byte fields are converted element-wise into a list of
 * encoded strings. The constructor is generated by Lombok's {@code @AllArgsConstructor}.</p>
 *
 * @see ProtoFieldFactory
 */
@AllArgsConstructor
public class ByteProtoField implements ProtoField {

    /**
     * Descriptor of the field, used to confirm that it is a {@code BYTES} field.
     */
    private final Descriptors.FieldDescriptor descriptor;
    /**
     * The raw field value: a {@link ByteString}, or a collection of them for repeated fields.
     */
    private final Object fieldValue;

    /**
     * Returns the base64-encoded form of the byte-field value.
     *
     * <p>A repeated field is converted into a list with each element encoded individually, while a
     * singular field is converted directly.</p>
     *
     * @return the base64-encoded string, or a list of such strings for repeated fields
     */
    @Override
    public Object getValue() {
        if (fieldValue instanceof Collection<?>) {
            return ((Collection<?>) fieldValue).stream().map(this::getByteString).collect(Collectors.toList());
        }
        return getByteString(fieldValue);
    }

    /**
     * Converts a single {@link ByteString} value to a base64-encoded string.
     *
     * <p>The byte string is first decoded as UTF-8 text and the resulting string's bytes are then
     * base64-encoded.</p>
     *
     * @param field the {@link ByteString} value to convert
     * @return the base64-encoded representation of the value
     */
    private Object getByteString(Object field) {
        ByteString byteString = (ByteString) field;
        byte[] bytes = byteString.toStringUtf8().getBytes();
        return base64Encode(bytes);
    }

    /**
     * Base64-encodes the given bytes.
     *
     * @param bytes the bytes to encode
     * @return the base64-encoded string
     */
    private String base64Encode(byte[] bytes) {
        return new String(Base64.getEncoder().encode(bytes));
    }

    /**
     * Indicates whether the field is a Protobuf {@code BYTES} field.
     *
     * @return {@code true} if the field's type is {@code BYTES}, {@code false} otherwise
     */
    @Override
    public boolean matches() {
        return descriptor.getType() == Descriptors.FieldDescriptor.Type.BYTES;
    }
}
