package com.gotocompany.depot.message.proto.converter.fields;

import lombok.AllArgsConstructor;

/**
 * Fallback {@link ProtoField} strategy that returns a field value unchanged.
 *
 * <p>This implementation is used by {@link ProtoFieldFactory} when no specialised strategy matches the
 * field. Its {@link #matches()} always returns {@code false}, so it is never chosen by matching;
 * instead the factory selects it explicitly as the default. The constructor is generated by Lombok's
 * {@code @AllArgsConstructor}.</p>
 *
 * @see ProtoFieldFactory
 * @see ProtoField
 */
@AllArgsConstructor
public class DefaultProtoField implements ProtoField {
    /**
     * The raw field value to be returned unchanged.
     */
    private final Object fieldValue;

    /**
     * Returns the wrapped field value unchanged.
     *
     * @return the raw field value supplied at construction
     */
    @Override
    public Object getValue() {
        return fieldValue;
    }

    /**
     * Always reports no match, since this strategy is only used as an explicit fallback.
     *
     * @return {@code false} always
     */
    @Override
    public boolean matches() {
        return false;
    }
}
