package com.gotocompany.depot.message.proto.converter.fields;

import com.google.protobuf.Descriptors;
import lombok.AllArgsConstructor;

import java.util.ArrayList;
import java.util.List;

/**
 * {@link ProtoField} strategy that converts Protobuf {@code ENUM} fields into their string names.
 *
 * <p>A singular enum value is rendered via its {@code toString()} (the enum value name); a repeated
 * enum field is converted into a list of such names. The constructor is generated by Lombok's
 * {@code @AllArgsConstructor}.</p>
 *
 * @see ProtoFieldFactory
 */
@AllArgsConstructor
public class EnumProtoField implements ProtoField {
    /**
     * Descriptor of the field, used to confirm that it is an {@code ENUM} field and to detect
     * repetition.
     */
    private final Descriptors.FieldDescriptor descriptor;
    /**
     * The raw field value: an {@link Descriptors.EnumValueDescriptor}, or a list of them for repeated
     * fields.
     */
    private final Object fieldValue;

    /**
     * Returns the enum field value rendered as its string name, or names.
     *
     * <p>For a repeated field each {@link Descriptors.EnumValueDescriptor} is converted to its name and
     * collected into a list; for a singular field the value's name is returned directly.</p>
     *
     * @return the enum value name, or a list of names for repeated fields
     */
    @Override
    public Object getValue() {
        if (descriptor.isRepeated()) {
            List<Descriptors.EnumValueDescriptor> enumValues = ((List<Descriptors.EnumValueDescriptor>) (fieldValue));
            List<String> enumStrValues = new ArrayList<>();
            for (Descriptors.EnumValueDescriptor enumVal : enumValues) {
                enumStrValues.add(enumVal.toString());
            }
            return enumStrValues;
        }
        return fieldValue.toString();
    }

    /**
     * Indicates whether the field is a Protobuf {@code ENUM} field.
     *
     * @return {@code true} if the field's type is {@code ENUM}, {@code false} otherwise
     */
    @Override
    public boolean matches() {
        return descriptor.getType() == Descriptors.FieldDescriptor.Type.ENUM;
    }
}
