package com.gotocompany.depot.message.proto.converter.fields;

import com.google.protobuf.Descriptors;
import lombok.AllArgsConstructor;

/**
 * {@link ProtoField} strategy for generic Protobuf message fields that returns the message value
 * unchanged.
 *
 * <p>This is the catch-all strategy for {@code MESSAGE}-typed fields that are not one of the
 * specially-handled well-known types. Because it matches any message, {@link ProtoFieldFactory} lists
 * it after the more specific message strategies (duration, timestamp and struct) so that those take
 * precedence. The constructor is generated by Lombok's {@code @AllArgsConstructor}.</p>
 *
 * @see ProtoFieldFactory
 * @see TimestampProtoField
 * @see DurationProtoField
 * @see StructProtoField
 */
@AllArgsConstructor
public class MessageProtoField implements ProtoField {
    /**
     * Descriptor of the field, used to confirm that it is a {@code MESSAGE} field.
     */
    private final Descriptors.FieldDescriptor descriptor;
    /**
     * The raw message value, returned unchanged by {@link #getValue()}.
     */
    private final Object fieldValue;

    /**
     * Returns the message field value unchanged.
     *
     * @return the raw field value supplied at construction
     */
    @Override
    public Object getValue() {
        return fieldValue;
    }

    /**
     * Indicates whether the field is a Protobuf {@code MESSAGE} field.
     *
     * @return {@code true} if the field's type is {@code MESSAGE}, {@code false} otherwise
     */
    @Override
    public boolean matches() {
        return descriptor.getType() == Descriptors.FieldDescriptor.Type.MESSAGE;
    }
}
