package com.gotocompany.depot.message.proto.converter.fields;

import com.google.protobuf.Descriptors;
import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.Message;
import com.google.protobuf.util.JsonFormat;
import lombok.AllArgsConstructor;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * {@link ProtoField} strategy that converts {@code google.protobuf.Struct} fields into their JSON
 * string form.
 *
 * <p>Each struct value is printed with a shared {@link JsonFormat.Printer} that preserves proto field
 * names and omits insignificant whitespace. Repeated struct fields are converted element-wise into a
 * list of JSON strings. If a value cannot be printed, an empty string is returned in its place. The
 * constructor is generated by Lombok's {@code @AllArgsConstructor}.</p>
 *
 * @see ProtoFieldFactory
 */
@AllArgsConstructor
public class StructProtoField implements ProtoField {
    /**
     * Shared, immutable Protobuf JSON printer that preserves proto field names and omits insignificant
     * whitespace.
     */
    private static JsonFormat.Printer printer = JsonFormat.printer()
            .preservingProtoFieldNames()
            .omittingInsignificantWhitespace();
    /**
     * Descriptor of the field, used to confirm that it is a {@code google.protobuf.Struct} field.
     */
    private final Descriptors.FieldDescriptor descriptor;
    /**
     * The raw field value: a struct {@link Message}, or a collection of them for repeated fields.
     */
    private final Object fieldValue;

    /**
     * Returns the struct field value rendered as one or more JSON strings.
     *
     * <p>A repeated field is converted into a list with each struct printed individually, while a
     * singular field is printed directly. If any value cannot be serialised, an empty string is
     * returned instead of propagating the error.</p>
     *
     * @return the JSON string for the struct, a list of JSON strings for repeated fields, or an empty
     *     string if serialisation fails
     */
    @Override
    public Object getValue() {
        try {
            if (fieldValue instanceof Collection<?>) {
                List<String> structStrValues = new ArrayList<>();
                for (Object field : (Collection<?>) fieldValue) {
                    structStrValues.add(getString(field));
                }
                return structStrValues;
            }
            return getString(fieldValue);
        } catch (InvalidProtocolBufferException e) {
            return "";
        }
    }

    /**
     * Prints a single struct value to its JSON string form.
     *
     * @param field the struct value to print, expected to be a Protobuf {@link Message}
     * @return the JSON representation of the struct
     * @throws InvalidProtocolBufferException if the struct cannot be converted to JSON
     */
    private String getString(Object field) throws InvalidProtocolBufferException {
        return printer.print((Message) field);
    }

    /**
     * Indicates whether the field is a {@code google.protobuf.Struct} message field.
     *
     * @return {@code true} if the field is a message whose type is {@code google.protobuf.Struct},
     *     {@code false} otherwise
     */
    @Override
    public boolean matches() {
        return descriptor.getType() == Descriptors.FieldDescriptor.Type.MESSAGE
                && descriptor.getMessageType().getFullName().equals(com.google.protobuf.Struct.getDescriptor().getFullName());
    }
}
