package com.gotocompany.depot.message.proto.converter.fields;

import com.google.protobuf.Descriptors;
import com.google.protobuf.DynamicMessage;
import lombok.AllArgsConstructor;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

/**
 * {@link ProtoField} strategy that converts {@code google.protobuf.Timestamp} fields into
 * {@link Instant} values.
 *
 * <p>The timestamp's {@code seconds} and {@code nanos} fields are read positionally from the dynamic
 * message and combined into an {@link Instant}. Repeated timestamp fields are converted element-wise
 * into a list of instants. The constructor is generated by Lombok's {@code @AllArgsConstructor}.</p>
 *
 * @see ProtoFieldFactory
 */
@AllArgsConstructor
public class TimestampProtoField implements ProtoField {
    /**
     * Descriptor of the field, used to confirm that it is a {@code google.protobuf.Timestamp} field.
     */
    private final Descriptors.FieldDescriptor descriptor;
    /**
     * The raw field value: a timestamp {@link DynamicMessage}, or a collection of them for repeated
     * fields.
     */
    private final Object fieldValue;

    /**
     * Returns the timestamp field value converted to one or more {@link Instant} values.
     *
     * <p>A repeated field is converted into a list with each timestamp converted individually, while a
     * singular field is converted directly.</p>
     *
     * @return the converted {@link Instant}, or a list of {@link Instant} for repeated fields
     */
    @Override
    public Object getValue() {
        if (fieldValue instanceof Collection<?>) {
            return ((Collection<?>) fieldValue).stream().map(this::getTime).collect(Collectors.toList());
        }
        return getTime(fieldValue);
    }

    /**
     * Converts a single timestamp message into an {@link Instant}.
     *
     * <p>The two fields of the dynamic timestamp message are read positionally: the first is treated
     * as the epoch seconds and the second as the nanosecond adjustment, and they are combined via
     * {@link Instant#ofEpochSecond(long, long)}.</p>
     *
     * @param field the timestamp value to convert, expected to be a {@link DynamicMessage}
     * @return the timestamp as an {@link Instant}
     */
    private Instant getTime(Object field) {
        DynamicMessage dynamicField = (DynamicMessage) field;
        List<Descriptors.FieldDescriptor> descriptors = dynamicField.getDescriptorForType().getFields();
        List<Object> timeFields = new ArrayList<>();
        descriptors.forEach(desc -> timeFields.add(dynamicField.getField(desc)));
        return Instant.ofEpochSecond((long) timeFields.get(0), ((Integer) timeFields.get(1)).longValue());
    }

    /**
     * Indicates whether the field is a {@code google.protobuf.Timestamp} message field.
     *
     * @return {@code true} if the field is a message whose type is {@code google.protobuf.Timestamp},
     *     {@code false} otherwise
     */
    @Override
    public boolean matches() {
        return descriptor.getType() == Descriptors.FieldDescriptor.Type.MESSAGE
                && descriptor.getMessageType().getFullName().equals(com.google.protobuf.Timestamp.getDescriptor().getFullName());
    }
}
