package com.gotocompany.depot.bigquery.client;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.cloud.TransportOptions;
import com.google.cloud.bigquery.BigQuery;
import com.google.cloud.bigquery.BigQueryException;
import com.google.cloud.bigquery.BigQueryOptions;
import com.google.cloud.bigquery.Clustering;
import com.google.cloud.bigquery.Dataset;
import com.google.cloud.bigquery.Field;
import com.google.cloud.bigquery.InsertAllRequest;
import com.google.cloud.bigquery.InsertAllResponse;
import com.google.cloud.bigquery.Schema;
import com.google.cloud.bigquery.StandardTableDefinition;
import com.google.cloud.bigquery.Table;
import com.google.cloud.bigquery.TableDefinition;
import com.google.cloud.bigquery.TableId;
import com.google.cloud.bigquery.TableInfo;
import com.google.cloud.bigquery.TimePartitioning;
import com.gotocompany.depot.bigquery.exception.BQDatasetLocationChangedException;
import com.gotocompany.depot.config.BigQuerySinkConfig;
import com.gotocompany.depot.metrics.BigQueryMetrics;
import com.gotocompany.depot.metrics.Instrumentation;
import lombok.Getter;

import java.io.FileInputStream;
import java.io.IOException;
import java.time.Instant;
import java.util.List;
import java.util.Random;

/**
 * Thin wrapper around the Google {@link BigQuery} service that manages the sink's destination dataset
 * and table and performs legacy streaming inserts.
 *
 * <p>This client is used by the BigQuery sink's legacy {@code insertAll} path. Its responsibilities
 * are:</p>
 * <ul>
 *     <li>Streaming rows into the table via {@link #insertAll(InsertAllRequest)}.</li>
 *     <li>Creating or updating the dataset and table to match the desired schema, labels,
 *     partitioning and clustering through {@link #upsertTable(List)}, retrying on rate-limit errors.</li>
 *     <li>Exposing the current table schema via {@link #getSchema()}.</li>
 *     <li>Emitting operation and latency metrics for each BigQuery API call.</li>
 * </ul>
 *
 * <p>Schema/table mutations are reconciled idempotently: the dataset and table are only created when
 * missing and only updated when a relevant difference (labels, schema, partition expiry or clustering)
 * is detected. Dataset location changes are rejected as they are not permitted by BigQuery.</p>
 *
 * <p>The {@code getTableID()} accessor is generated by Lombok via {@link Getter}.</p>
 */
public class BigQueryClient {
    /** Maximum number of attempts when upserting the dataset/table under rate limiting. */
    private static final int TABLE_INFO_UPDATE_RETRIES = 10;
    /** Upper bound, in milliseconds, for the randomized back-off sleep between retries. */
    private static final int DEFAULT_SLEEP_RETRY = 10000;
    /** The underlying Google BigQuery service client. */
    private final BigQuery bigquery;
    /** Identifier of the destination table (dataset and table name). */
    @Getter
    private final TableId tableID;
    /** Sink configuration providing dataset/table names, labels and partitioning/clustering options. */
    private final BigQuerySinkConfig bqConfig;
    /** Helper that builds the table definition (schema, partitioning, clustering) for upserts. */
    private final BigQueryTableDefinition bigQueryTableDefinition;
    /** Instrumentation used for logging and metric emission. */
    private final Instrumentation instrumentation;
    /** Source of randomized back-off durations for retrying rate-limited upserts. */
    private final Random random = new Random(System.currentTimeMillis());
    /** Provider of BigQuery metric names and tag templates. */
    private final BigQueryMetrics bigqueryMetrics;

    /**
     * Creates a client backed by a freshly constructed BigQuery service derived from the configuration.
     *
     * @param bqConfig        the BigQuery sink configuration
     * @param bigQueryMetrics the provider of BigQuery metric names and tags
     * @param instrumentation the instrumentation used for logging and metric emission
     * @throws IOException if the BigQuery service cannot be created, for example when the credentials
     *                     cannot be read
     */
    public BigQueryClient(BigQuerySinkConfig bqConfig, BigQueryMetrics bigQueryMetrics, Instrumentation instrumentation) throws IOException {
        this(getBigQueryInstance(bqConfig), bqConfig, bigQueryMetrics, instrumentation);
    }

    /**
     * Creates a client around an already-constructed BigQuery service.
     *
     * <p>This constructor is primarily useful for testing with a supplied (or mocked) service. The
     * destination {@link TableId} and the {@link BigQueryTableDefinition} helper are derived from the
     * configuration.</p>
     *
     * @param bq              the BigQuery service to use
     * @param bqConfig        the BigQuery sink configuration
     * @param bigQueryMetrics the provider of BigQuery metric names and tags
     * @param instrumentation the instrumentation used for logging and metric emission
     */
    public BigQueryClient(BigQuery bq, BigQuerySinkConfig bqConfig, BigQueryMetrics bigQueryMetrics, Instrumentation instrumentation) {
        this.bigquery = bq;
        this.bqConfig = bqConfig;
        this.tableID = TableId.of(bqConfig.getDatasetName(), bqConfig.getTableName());
        this.bigQueryTableDefinition = new BigQueryTableDefinition(bqConfig);
        this.instrumentation = instrumentation;
        this.bigqueryMetrics = bigQueryMetrics;
    }

    /**
     * Builds a {@link BigQuery} service from the configuration's credentials, project and timeouts.
     *
     * @param sinkConfig the configuration providing the credential path, project ID and HTTP timeouts
     * @return a configured BigQuery service instance
     * @throws IOException if the credentials file cannot be read
     */
    private static BigQuery getBigQueryInstance(BigQuerySinkConfig sinkConfig) throws IOException {
        TransportOptions transportOptions = BigQueryOptions.getDefaultHttpTransportOptions().toBuilder()
                .setConnectTimeout(sinkConfig.getBqClientConnectTimeoutMS())
                .setReadTimeout(sinkConfig.getBqClientReadTimeoutMS())
                .build();
        return BigQueryOptions.newBuilder()
                .setTransportOptions(transportOptions)
                .setCredentials(GoogleCredentials.fromStream(new FileInputStream(sinkConfig.getBigQueryCredentialPath())))
                .setProjectId(sinkConfig.getGCloudProjectID())
                .build().getService();
    }

    /**
     * Streams the given rows into the destination table and records the insert metric.
     *
     * @param rows the insert-all request describing the rows to stream
     * @return the response reporting per-row insertion status (including any per-row errors)
     */
    public InsertAllResponse insertAll(InsertAllRequest rows) {
        Instant start = Instant.now();
        InsertAllResponse response = bigquery.insertAll(rows);
        instrument(start, BigQueryMetrics.BigQueryAPIType.TABLE_INSERT_ALL);
        return response;
    }

    /**
     * Creates or updates the destination dataset and table so they match the supplied schema fields.
     *
     * <p>Wraps the schema fields in a {@link Schema}, builds the table definition (including
     * partitioning and clustering per configuration), attaches the configured table labels and
     * reconciles the dataset and table with retries on rate-limit errors.</p>
     *
     * @param bqSchemaFields the desired list of BigQuery schema fields for the table
     * @throws BigQueryException if a non-retryable BigQuery error occurs while upserting the dataset or
     *                           table
     */
    public void upsertTable(List<Field> bqSchemaFields) throws BigQueryException {
        Schema schema = Schema.of(bqSchemaFields);
        TableDefinition tableDefinition = getTableDefinition(schema);
        TableInfo tableInfo = TableInfo.newBuilder(tableID, tableDefinition)
                .setLabels(bqConfig.getTableLabels())
                .build();
        upsertDatasetAndTableWithRetry(tableInfo);
    }

    /**
     * Returns the current schema of the destination table.
     *
     * @return the table's schema, or an empty {@link Schema} if the table does not exist
     */
    public Schema getSchema() {
        Table table = bigquery.getTable(tableID);
        if (table == null) {
            return Schema.of();
        }
        return table.getDefinition().getSchema();
    }

    /**
     * Attempts to upsert the dataset and table, retrying with randomized back-off on rate limiting.
     *
     * <p>Retries up to {@value #TABLE_INFO_UPDATE_RETRIES} times. On a {@link BigQueryException} whose
     * message indicates exceeded rate limits, the method sleeps for a random interval (bounded by
     * {@value #DEFAULT_SLEEP_RETRY} milliseconds) and retries; any other exception is rethrown
     * immediately. An interruption during the back-off sleep is recorded as a non-fatal error.</p>
     *
     * @param info the table information (definition and labels) to reconcile
     * @throws BigQueryException if a non-retryable BigQuery error occurs during an attempt
     */
    private void upsertDatasetAndTableWithRetry(TableInfo info) {
        for (int ii = 0; ii < TABLE_INFO_UPDATE_RETRIES; ii++) {
            try {
                upsertDatasetAndTable(info);
                return;
            } catch (BigQueryException e) {
                instrumentation.logWarn(e.getMessage());
                if (e.getMessage().contains("Exceeded rate limits")) {
                    try {
                        int sleepMillis = random.nextInt(DEFAULT_SLEEP_RETRY);
                        instrumentation.logInfo("Waiting for " + sleepMillis + " milliseconds");
                        Thread.sleep(sleepMillis);
                    } catch (InterruptedException interruptedException) {
                        instrumentation.captureNonFatalError(bigqueryMetrics.getErrorEventMetric(), interruptedException, "Sleep interrupted");
                    }
                } else {
                    throw e;
                }
            }
        }
    }

    /**
     * Reconciles the dataset and table in a single pass, creating or updating each only as needed.
     *
     * <p>The dataset is created (with the configured location and labels) when it does not exist; if it
     * exists, it is updated only when {@link #shouldUpdateDataset(Dataset)} reports a label change. The
     * table is created when missing; if it exists, it is updated only when
     * {@link #shouldUpdateTable(TableInfo, Table, Schema, Schema)} detects a relevant difference,
     * otherwise the update is skipped. Each performed operation is instrumented.</p>
     *
     * @param tableInfo the desired table information (definition and labels)
     * @throws com.gotocompany.depot.bigquery.exception.BQDatasetLocationChangedException if the existing
     *         dataset's location differs from the configured location
     * @throws BigQueryException if the underlying create/update calls fail
     */
    private void upsertDatasetAndTable(TableInfo tableInfo) {
        Dataset dataSet = bigquery.getDataset(tableID.getDataset());
        if (dataSet == null || !bigquery.getDataset(tableID.getDataset()).exists()) {
            Instant start = Instant.now();
            bigquery.create(
                    Dataset.newBuilder(tableID.getDataset())
                            .setLocation(bqConfig.getBigQueryDatasetLocation())
                            .setLabels(bqConfig.getDatasetLabels())
                            .build()
            );
            instrumentation.logInfo("Successfully CREATED bigquery DATASET: {}", tableID.getDataset());
            instrument(start, BigQueryMetrics.BigQueryAPIType.DATASET_CREATE);
        } else if (shouldUpdateDataset(dataSet)) {
            Instant start = Instant.now();
            bigquery.update(
                    Dataset.newBuilder(tableID.getDataset())
                            .setLabels(bqConfig.getDatasetLabels())
                            .build()
            );
            instrumentation.logInfo("Successfully UPDATED bigquery DATASET: {} with labels", tableID.getDataset());
            instrument(start, BigQueryMetrics.BigQueryAPIType.DATASET_UPDATE);
        }

        Table table = bigquery.getTable(tableID);
        if (table == null || !table.exists()) {
            Instant start = Instant.now();
            bigquery.create(tableInfo);
            instrumentation.logInfo("Successfully CREATED bigquery TABLE: {}", tableID.getTable());
            instrument(start, BigQueryMetrics.BigQueryAPIType.TABLE_CREATE);
        } else {
            Schema existingSchema = table.getDefinition().getSchema();
            Schema updatedSchema = tableInfo.getDefinition().getSchema();

            if (shouldUpdateTable(tableInfo, table, existingSchema, updatedSchema)) {
                Instant start = Instant.now();
                bigquery.update(tableInfo);
                instrumentation.logInfo("Successfully UPDATED bigquery TABLE: {}", tableID.getTable());
                instrument(start, BigQueryMetrics.BigQueryAPIType.TABLE_UPDATE);
            } else {
                instrumentation.logInfo("Skipping bigquery table update, since proto schema hasn't changed");
            }
        }
    }

    /**
     * Emits the operation counter and latency metrics for a BigQuery API operation.
     *
     * <p>Increments the operation-total counter and captures the duration since {@code startTime}, both
     * tagged with the table, dataset, project and the supplied API type.</p>
     *
     * @param startTime the instant the operation began, used to compute its latency
     * @param type      the BigQuery API operation type used as the metric's API tag
     */
    private void instrument(Instant startTime, BigQueryMetrics.BigQueryAPIType type) {
        instrumentation.incrementCounter(
                bigqueryMetrics.getBigqueryOperationTotalMetric(),
                String.format(BigQueryMetrics.BIGQUERY_TABLE_TAG, tableID.getTable()),
                String.format(BigQueryMetrics.BIGQUERY_DATASET_TAG, tableID.getDataset()),
                String.format(BigQueryMetrics.BIGQUERY_PROJECT_TAG, tableID.getProject()),
                String.format(BigQueryMetrics.BIGQUERY_API_TAG, type));
        instrumentation.captureDurationSince(
                bigqueryMetrics.getBigqueryOperationLatencyMetric(),
                startTime,
                String.format(BigQueryMetrics.BIGQUERY_TABLE_TAG, tableID.getTable()),
                String.format(BigQueryMetrics.BIGQUERY_DATASET_TAG, tableID.getDataset()),
                String.format(BigQueryMetrics.BIGQUERY_PROJECT_TAG, tableID.getProject()),
                String.format(BigQueryMetrics.BIGQUERY_API_TAG, type));
    }

    /**
     * Determines whether an existing table needs to be updated.
     *
     * @param tableInfo      the desired table information
     * @param table          the existing table
     * @param existingSchema the schema currently on the table
     * @param updatedSchema  the desired schema
     * @return {@code true} if the labels differ, the schema differs, the partition expiry must change,
     *         or the clustering keys must change; {@code false} otherwise
     */
    private boolean shouldUpdateTable(TableInfo tableInfo, Table table, Schema existingSchema, Schema updatedSchema) {
        return !table.getLabels().equals(tableInfo.getLabels())
                || !existingSchema.equals(updatedSchema)
                || shouldChangePartitionExpiryForStandardTable(table)
                || shouldUpdateClusteringKeys(table);
    }

    /**
     * Determines whether an existing dataset needs a label update, rejecting location changes.
     *
     * @param dataSet the existing dataset
     * @return {@code true} if the dataset's labels differ from the configured labels, {@code false}
     *         otherwise
     * @throws com.gotocompany.depot.bigquery.exception.BQDatasetLocationChangedException if the existing
     *         dataset's location differs from the configured location
     */
    private boolean shouldUpdateDataset(Dataset dataSet) {
        if (!dataSet.getLocation().equals(bqConfig.getBigQueryDatasetLocation())) {
            throw new BQDatasetLocationChangedException("Dataset location cannot be changed from "
                    + dataSet.getLocation() + " to " + bqConfig.getBigQueryDatasetLocation());
        }

        return !dataSet.getLabels().equals(bqConfig.getDatasetLabels());
    }

    /**
     * Determines whether the table's time-partition expiry must be changed to match the configuration.
     *
     * <p>Only standard tables are considered; non-tables and unpartitioned tables never require an
     * expiry change. The current expiry (treating {@code null} as "never expire") is compared against
     * the configured expiry (treating a non-positive value as "never expire").</p>
     *
     * @param table the existing table to inspect
     * @return {@code true} if the current partition expiry differs from the configured expiry,
     *         {@code false} otherwise
     */
    private boolean shouldChangePartitionExpiryForStandardTable(Table table) {
        if (!isTable(table)) {
            return false;
        }
        TimePartitioning timePartitioning = ((StandardTableDefinition) (table.getDefinition())).getTimePartitioning();
        if (timePartitioning == null) {
            // If the table is not partitioned already, no need to update the table
            return false;
        }
        long neverExpireMs = 0L;
        Long currentExpirationMs = timePartitioning.getExpirationMs() == null ? neverExpireMs : timePartitioning.getExpirationMs();
        Long newExpirationMs = bqConfig.getBigQueryTablePartitionExpiryMS() > 0 ? bqConfig.getBigQueryTablePartitionExpiryMS() : neverExpireMs;
        return !currentExpirationMs.equals(newExpirationMs);
    }

    /**
     * Determines whether the table's clustering keys must be changed to match the configuration.
     *
     * <p>Only standard tables are considered. If the table is already clustered, the existing keys are
     * compared with the configured keys (when clustering is enabled), and a difference triggers an
     * update; if clustering is disabled the existing clustering is left as-is. If the table is not
     * clustered, an update is required only when clustering is enabled in the configuration.</p>
     *
     * @param table the existing table to inspect
     * @return {@code true} if the clustering configuration differs from the table's current clustering,
     *         {@code false} otherwise
     */
    private boolean shouldUpdateClusteringKeys(Table table) {
        if (!isTable(table)) {
            return false;
        }
        Clustering clustering = ((StandardTableDefinition) (table.getDefinition())).getClustering();
        if (clustering != null) {
            List<String> existingClusteringKeys = clustering.getFields();
            if (bqConfig.isTableClusteringEnabled()) {
                List<String> updatedClusteringKeys = bqConfig.getTableClusteringKeys();
                return !existingClusteringKeys.equals(updatedClusteringKeys);
            } else {
                return false;
            }
        } else {
            return bqConfig.isTableClusteringEnabled();
        }
    }

    /**
     * Determines whether the given table is a standard table (as opposed to a view or other type).
     *
     * @param table the table to inspect
     * @return {@code true} if the table's definition type is
     *         {@link StandardTableDefinition.Type#TABLE}, {@code false} otherwise
     */
    private boolean isTable(Table table) {
        return table.getDefinition().getType().equals(StandardTableDefinition.Type.TABLE);
    }

    /**
     * Builds the table definition for the given schema by delegating to {@link BigQueryTableDefinition}.
     *
     * @param schema the schema to build the table definition from
     * @return the resulting table definition including any configured partitioning and clustering
     */
    private TableDefinition getTableDefinition(Schema schema) {
        return bigQueryTableDefinition.getTableDefinition(schema);
    }
}
