package com.gotocompany.depot.bigquery.client;

import com.google.cloud.bigquery.Clustering;
import com.google.cloud.bigquery.Field;
import com.google.cloud.bigquery.LegacySQLTypeName;
import com.google.cloud.bigquery.Schema;
import com.google.cloud.bigquery.StandardTableDefinition;
import com.google.cloud.bigquery.TimePartitioning;
import com.gotocompany.depot.bigquery.exception.BQClusteringKeysException;
import com.gotocompany.depot.bigquery.exception.BQPartitionKeyNotSpecified;
import com.gotocompany.depot.config.BigQuerySinkConfig;
import lombok.AllArgsConstructor;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Builds the BigQuery {@link StandardTableDefinition} for the sink's destination table from a schema
 * and the configured partitioning and clustering options.
 *
 * <p>Given a {@link Schema}, this class produces a table definition that optionally enables
 * time-based partitioning and clustering according to the {@link BigQuerySinkConfig}. It also enforces
 * the constraints BigQuery (and Depot) impose on those features, such as requiring a valid partition
 * key of a date/timestamp type and limiting the number of clustering keys.</p>
 *
 * <p>The all-arguments constructor is generated by Lombok via {@link AllArgsConstructor}.</p>
 *
 * @see BigQueryClient#upsertTable(java.util.List)
 */
@AllArgsConstructor
public class BigQueryTableDefinition {

    /** Maximum number of clustering keys allowed by BigQuery for a table. */
    private static final int MAX_CLUSTERING_KEYS = 4;
    /** Sink configuration supplying partitioning and clustering options and the table name. */
    private final BigQuerySinkConfig bqConfig;

    /**
     * Builds a {@link StandardTableDefinition} for the given schema, applying partitioning and
     * clustering when enabled.
     *
     * <p>The schema is always set on the definition. Time partitioning is added when partitioning is
     * enabled in the configuration, and clustering is added when clustering is enabled.</p>
     *
     * @param schema the BigQuery schema describing the table's columns
     * @return the assembled standard table definition
     * @throws com.gotocompany.depot.bigquery.exception.BQPartitionKeyNotSpecified if partitioning is
     *         enabled but the partition key is missing or absent from the schema
     * @throws UnsupportedOperationException if partitioning is enabled but the partition field is not a
     *         {@code DATE} or {@code TIMESTAMP} type
     * @throws com.gotocompany.depot.bigquery.exception.BQClusteringKeysException if clustering is
     *         enabled but the clustering keys are invalid (empty, too many, or missing from the schema)
     */
    public StandardTableDefinition getTableDefinition(Schema schema) {
        StandardTableDefinition.Builder tableDefinitionBuilder = StandardTableDefinition.newBuilder().setSchema(schema);
        if (bqConfig.isTablePartitioningEnabled()) {
            TimePartitioning partitioning = getPartitionedTableDefinition(schema);
            tableDefinitionBuilder.setTimePartitioning(partitioning);
        }
        if (bqConfig.isTableClusteringEnabled()) {
            Clustering clustering = getClusteredTableDefinition(schema);
            tableDefinitionBuilder.setClustering(clustering);
        }
        return tableDefinitionBuilder.build();
    }

    /**
     * Builds the day-based {@link TimePartitioning} for the table from the configured partition key.
     *
     * <p>Validates that a partition key is configured and present in the schema, and that the
     * corresponding field is of a {@code TIMESTAMP} or {@code DATE} type. The partitioning requires a
     * partition filter on queries, and applies the configured partition expiry (treating a non-positive
     * expiry as "never expire" by leaving the expiration unset).</p>
     *
     * @param schema the schema in which the partition field must exist
     * @return the day-partitioning definition for the configured partition key
     * @throws com.gotocompany.depot.bigquery.exception.BQPartitionKeyNotSpecified if the partition key
     *         is {@code null} or not present in the schema
     * @throws UnsupportedOperationException if the partition field is not a {@code DATE} or
     *         {@code TIMESTAMP} type (range partitioning is unsupported)
     */
    private TimePartitioning getPartitionedTableDefinition(Schema schema) {
        String tablePartitionKey = bqConfig.getTablePartitionKey();
        if (tablePartitionKey == null) {
            throw new BQPartitionKeyNotSpecified(String.format("Partition key not specified for the table: %s", bqConfig.getTableName()));
        }
        Optional<Field> partitionFieldOptional = schema.getFields()
                .stream()
                .filter(obj -> tablePartitionKey.equals(obj.getName()))
                .findFirst();
        if (!partitionFieldOptional.isPresent()) {
            throw new BQPartitionKeyNotSpecified(String.format("Partition key %s is not present in the schema", tablePartitionKey));
        }
        Field partitionField = partitionFieldOptional.get();
        if (partitionField.getType() == LegacySQLTypeName.TIMESTAMP || partitionField.getType() == LegacySQLTypeName.DATE) {
            Long partitionExpiry = bqConfig.getBigQueryTablePartitionExpiryMS();
            return TimePartitioning.newBuilder(TimePartitioning.Type.DAY)
                    .setField(tablePartitionKey)
                    .setRequirePartitionFilter(true)
                    .setExpirationMs(partitionExpiry <= 0 ? null : partitionExpiry)
                    .build();
        } else {
            throw new UnsupportedOperationException("Range BigQuery partitioning is not supported, supported partition fields have to be of DATE or TIMESTAMP type");
        }
    }

    /**
     * Builds the {@link Clustering} definition for the table from the configured clustering keys.
     *
     * <p>Validates that at least one clustering key is configured, that the number of keys does not
     * exceed {@value #MAX_CLUSTERING_KEYS}, and that every clustering key exists as a (non-nested)
     * field in the schema.</p>
     *
     * @param schema the schema whose top-level fields must contain all clustering keys
     * @return the clustering definition listing the configured key columns
     * @throws com.gotocompany.depot.bigquery.exception.BQClusteringKeysException if no keys are
     *         configured, if more than {@value #MAX_CLUSTERING_KEYS} keys are configured, or if any key
     *         is missing from the schema (or refers to an unsupported nested field)
     */
    private Clustering getClusteredTableDefinition(Schema schema) {
        if (bqConfig.getTableClusteringKeys().isEmpty()) {
            throw new BQClusteringKeysException(String.format("Clustering key not specified for the table: %s", bqConfig.getTableName()));
        }
        List<String> columnNames = bqConfig.getTableClusteringKeys();
        if (columnNames.size() > MAX_CLUSTERING_KEYS) {
            throw new BQClusteringKeysException(String.format("Max number of columns for clustering is %d", MAX_CLUSTERING_KEYS));
        }
        List<String> fieldNames = schema.getFields().stream().map(Field::getName).collect(Collectors.toList());
        if (!fieldNames.containsAll(columnNames)) {
            throw new BQClusteringKeysException(String.format("One or more column names specified %s not exist on the schema or a nested type which is not supported for clustering", columnNames));
        }
        return Clustering.newBuilder().setFields(columnNames).build();
    }
}
