package com.gotocompany.depot.message.proto;

import com.google.protobuf.DescriptorProtos;
import lombok.EqualsAndHashCode;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Mutable model of a Protobuf field (or message) and its nested structure, representing a schema as a
 * tree that is independent of the Protobuf descriptor API.
 *
 * <p>Each instance captures a field's name, declared type and label, its field number
 * ({@code index}) and, for message types, the list of child {@link ProtoField}s describing the nested
 * message. {@link ProtoFieldParser} populates these trees and {@link ProtoMapper} serialises them
 * into the JSON column-mapping format consumed by schema-aware sinks.</p>
 *
 * <p>Equality and hashing are generated by Lombok's {@code @EqualsAndHashCode} over all fields. The
 * type is not thread-safe; its child list is mutated through {@link #addField(ProtoField)}.</p>
 *
 * @see ProtoFieldParser
 * @see ProtoMapper
 */
@EqualsAndHashCode
public class ProtoField {
    /**
     * The field's name as declared in the {@code .proto} definition.
     */
    private String name;
    /**
     * Fully qualified type name for message or enum fields (for example
     * {@code .google.protobuf.Timestamp}); empty or {@code null} for scalar fields.
     */
    private String typeName;
    /**
     * The Protobuf field type, such as {@code TYPE_MESSAGE} or {@code TYPE_STRING}.
     */
    private DescriptorProtos.FieldDescriptorProto.Type type;
    /**
     * The Protobuf field label indicating optional, required or repeated cardinality.
     */
    private DescriptorProtos.FieldDescriptorProto.Label label;
    /**
     * Child fields describing the nested message structure; empty for scalar fields.
     */
    private List<ProtoField> fields;
    /**
     * The field number ({@code index}) assigned to this field within its message.
     */
    private int index;

    /**
     * Creates an empty field with no metadata and an empty child list.
     *
     * <p>This is typically used as the root container that {@link ProtoFieldParser} subsequently
     * populates with parsed child fields.</p>
     */
    public ProtoField() {
        this.fields = new ArrayList<>();
    }

    /**
     * Creates a fully specified field with the given metadata and child list.
     *
     * @param name the field name
     * @param typeName the fully qualified type name for message or enum fields, or an empty string
     *     for scalar fields
     * @param type the Protobuf field type
     * @param label the Protobuf field label (cardinality)
     * @param fields the list of child fields describing the nested message structure
     * @param index the field number assigned to this field
     */
    public ProtoField(String name, String typeName, DescriptorProtos.FieldDescriptorProto.Type type, DescriptorProtos.FieldDescriptorProto.Label label, List<ProtoField> fields, int index) {
        this.name = name;
        this.typeName = typeName;
        this.type = type;
        this.label = label;
        this.fields = fields;
        this.index = index;
    }

    /**
     * Creates a field model from a Protobuf {@code FieldDescriptorProto}.
     *
     * <p>The name, type, label, field number and type name are copied from the descriptor and the
     * child list is initialised empty, ready to be populated for nested message types.</p>
     *
     * @param f the Protobuf field descriptor whose metadata is copied into this model
     */
    public ProtoField(DescriptorProtos.FieldDescriptorProto f) {
        this.name = f.getName();
        this.type = f.getType();
        this.label = f.getLabel();
        this.index = f.getNumber();
        this.fields = new ArrayList<>();
        this.typeName = f.getTypeName();
    }

    /**
     * Determines whether this field represents a nested message that should be expanded into child
     * fields.
     *
     * <p>When a type name is present, the field is considered nested only if it is of message type and
     * is neither {@code google.protobuf.Timestamp} nor {@code google.protobuf.Struct}, since those are
     * handled as logical values rather than expanded. When no type name is present, the field is
     * considered nested whenever its type is {@code TYPE_MESSAGE}.</p>
     *
     * @return {@code true} if this field is a nested message to be expanded, {@code false} otherwise
     */
    public boolean isNested() {
        if (this.typeName != null && !this.typeName.equals("")) {
            return !typeName.equals(Constants.ProtobufTypeName.TIMESTAMP_PROTOBUF_TYPE_NAME)
                    && !typeName.equals(Constants.ProtobufTypeName.STRUCT_PROTOBUF_TYPE_NAME)
                    && type == DescriptorProtos.FieldDescriptorProto.Type.TYPE_MESSAGE;
        }
        return type == DescriptorProtos.FieldDescriptorProto.Type.TYPE_MESSAGE;
    }

    /**
     * Appends a child field to this field's list of nested fields.
     *
     * @param field the child field to add
     */
    public void addField(ProtoField field) {
        this.fields.add(field);
    }

    /**
     * Returns a debug string summarising this field's name, type, child count and nested children.
     *
     * @return a human-readable representation of this field and its descendants
     */
    @Override
    public String toString() {
        return "{"
                + "name='" + name + '\''
                + ", type=" + type
                + ", len=" + fields.size()
                + ", nested=" + Arrays.toString(fields.toArray())
                + '}';
    }

    /**
     * Returns the live list of child fields describing the nested message.
     *
     * @return the list of child {@link ProtoField}s, empty for scalar fields
     */
    public List<ProtoField> getFields() {
        return fields;
    }

    /**
     * Returns the field number assigned to this field.
     *
     * @return the field's index (number)
     */
    public int getIndex() {
        return index;
    }

    /**
     * Returns the field's name.
     *
     * @return the field name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the field's label (cardinality).
     *
     * @return the Protobuf field label
     */
    public DescriptorProtos.FieldDescriptorProto.Label getLabel() {
        return label;
    }

    /**
     * Returns the field's Protobuf type.
     *
     * @return the Protobuf field type
     */
    public DescriptorProtos.FieldDescriptorProto.Type getType() {
        return type;
    }

    /**
     * Returns the fully qualified type name for message or enum fields.
     *
     * @return the type name, or an empty string for scalar fields
     */
    public String getTypeName() {
        return typeName;
    }
}
