package com.gotocompany.depot.maxcompute.model;

import com.aliyun.odps.Column;
import com.aliyun.odps.TableSchema;
import com.aliyun.odps.type.TypeInfo;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.Map;

/**
 * Aggregates the resolved MaxCompute table definition used by the sink: the full {@link TableSchema}
 * (data, metadata, and partition columns) alongside a lookup of the metadata columns that Depot
 * injects into each row.
 *
 * <p>An instance is the single in-memory description of the destination table that the sink writes
 * against. It is built by {@link com.gotocompany.depot.maxcompute.schema.MaxComputeSchemaBuilder}
 * from a Protobuf descriptor and refreshed by
 * {@link com.gotocompany.depot.maxcompute.schema.MaxComputeSchemaCache} whenever the upstream schema
 * changes. The all-arguments constructor and the {@code getTableSchema()} and
 * {@code getMetadataColumns()} accessors are generated by Lombok.</p>
 */
@RequiredArgsConstructor
@Getter
public class MaxComputeSchema {

    /**
     * The complete MaxCompute table schema (data columns, metadata columns, and any partition
     * column) that the sink reads from and writes to. Exposed via the Lombok-generated
     * {@code getTableSchema()} accessor.
     */
    private final TableSchema tableSchema;
    /**
     * Lookup of metadata column name to its MaxCompute {@link TypeInfo}, describing the extra columns
     * Depot adds to carry message metadata. Exposed via the Lombok-generated
     * {@code getMetadataColumns()} accessor.
     */
    private final Map<String, TypeInfo> metadataColumns;

    /**
     * Returns the table's data columns as an array, preserving the order of the underlying
     * {@link TableSchema}.
     *
     * <p>Only regular (non-partition) columns are returned; partition columns held separately by the
     * schema are not included.</p>
     *
     * @return an array containing the table's non-partition {@link Column} definitions
     */
    public Column[] getColumns() {
        return tableSchema.getColumns().toArray(new Column[]{});
    }

}
