package com.gotocompany.depot.maxcompute.model;

import com.aliyun.odps.type.NestedTypeInfo;
import com.aliyun.odps.type.TypeInfo;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.apache.commons.lang.StringUtils;

/**
 * Value object that describes a single MaxCompute column (including columns nested inside
 * {@code STRUCT} and array-of-struct types) together with enough positional context to render the
 * column as a fully-qualified DDL fragment.
 *
 * <p>Instances are produced while flattening a {@link com.aliyun.odps.TableSchema} into its
 * individual (possibly nested) columns so that two schemas can be compared field by field. Each
 * detail records the dotted {@code prefix} path of the enclosing struct(s), the leaf column
 * {@code name}, the column {@link TypeInfo}, and whether the column is reached through an array
 * element. The {@link #getFullName()} and {@link #getDDL()} helpers then reconstruct the
 * backtick-quoted column path and the space-separated name-and-type DDL form used when emitting
 * {@code ALTER TABLE ... ADD COLUMN} statements.</p>
 *
 * <p>The all-arguments constructor is generated by Lombok. This type is primarily consumed by
 * {@link com.gotocompany.depot.maxcompute.schema.SchemaDifferenceUtils}, which is itself deprecated
 * pending official schema-evolution support.</p>
 */
@AllArgsConstructor
public class MaxComputeColumnDetail {
    /**
     * Dotted path of the enclosing struct column(s), or blank when the column sits at the top level
     * of the table. Combined with {@link #name} (and an {@code .element} segment for array elements)
     * by {@link #getFullName()} to form the fully-qualified column path.
     */
    private String prefix;
    /**
     * Leaf name of the column or struct field, rendered backtick-quoted in the generated path.
     */
    private String name;
    /**
     * MaxCompute {@link TypeInfo} of the column; exposed through the Lombok-generated
     * {@code getTypeInfo()} accessor.
     */
    @Getter
    private TypeInfo typeInfo;
    /**
     * Indicates whether this column is reached as the element of an array (an array-of-struct
     * field). When {@code true}, an {@code .element} segment is inserted into the generated path to
     * mirror MaxCompute's nested-field addressing.
     */
    private boolean isArrayElement;

    /**
     * Builds the DDL fragment that declares this column, formatted as the column path followed by a
     * space and the column type.
     *
     * <p>When the column is a nested type (for example a struct or array) the type is rendered using
     * {@link NestedTypeInfo}'s fully-expanded type name (the {@code getTypeName(true)} form);
     * otherwise the type's plain {@code toString()} representation is used. The leading column path
     * is produced by {@link #getFullName()}.</p>
     *
     * @return the column declaration fragment suitable for embedding in an
     *         {@code ALTER TABLE ... ADD COLUMN} statement
     */
    public String getDDL() {
        String typeInfoRepresentation = typeInfo instanceof NestedTypeInfo ? ((NestedTypeInfo) typeInfo).getTypeName(true) : typeInfo.toString();
        return String.format("%s %s", getFullName(), typeInfoRepresentation);
    }

    /**
     * Reconstructs the fully-qualified, backtick-quoted path that addresses this column within its
     * table.
     *
     * <p>For a top-level column (blank {@link #prefix}) the result is simply the backtick-quoted
     * {@link #name}. For a nested column the result joins, with dots, the {@code prefix}, an optional
     * {@code .element} segment when {@link #isArrayElement} is {@code true} (to step into an array's
     * element), and the backtick-quoted {@code name}.</p>
     *
     * @return the backtick-quoted, fully-qualified column path
     */
    public String getFullName() {
        return StringUtils.isBlank(prefix) ? String.format("`%s`", name) : String.format("%s%s.`%s`", prefix, isArrayElement ? ".element" : "", name);
    }
}
