package com.gotocompany.depot.maxcompute.model;

import com.google.protobuf.Descriptors;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * Lightweight carrier that bundles a Protobuf field with the context the MaxCompute converters need
 * to translate it, either into a MaxCompute {@link com.aliyun.odps.type.TypeInfo} (schema building)
 * or into a MaxCompute column value (record building).
 *
 * <p>It holds three pieces of state: the Protobuf {@link Descriptors.FieldDescriptor} that describes
 * the field, the already-parsed value to be converted ({@code parsedObject}, which is {@code null}
 * during schema construction where only the type matters), and the nesting {@code level} of the
 * field within the message tree ({@code 0} at the root). The level lets converters apply behaviour
 * that is only valid for top-level fields, such as timestamp partition-key validation.</p>
 *
 * <p>All three properties are exposed through Lombok-generated accessors, and the all-arguments
 * constructor is generated by Lombok. The convenience constructors default {@code parsedObject} to
 * {@code null} for type-only conversions.</p>
 *
 * @see com.gotocompany.depot.maxcompute.converter.ProtobufConverterOrchestrator
 */
@RequiredArgsConstructor
@Getter
public class ProtoPayload {
    /**
     * Protobuf descriptor of the field being converted; drives both type resolution and value
     * extraction. Exposed via the Lombok-generated {@code getFieldDescriptor()} accessor.
     */
    private final Descriptors.FieldDescriptor fieldDescriptor;
    /**
     * The parsed field value to convert into a MaxCompute column value, or {@code null} when the
     * payload is used purely for schema/type resolution. Exposed via the Lombok-generated
     * {@code getParsedObject()} accessor.
     */
    private final Object parsedObject;
    /**
     * Depth of the field within the Protobuf message tree, where {@code 0} denotes a root-level
     * field. Exposed via the Lombok-generated {@code getLevel()} accessor.
     */
    private final int level;

    /**
     * Creates a root-level, type-only payload for the given field.
     *
     * <p>The parsed value is set to {@code null} and the level to {@code 0}; this form is used when
     * only the field's type is required, for example while building the table schema.</p>
     *
     * @param fieldDescriptor the Protobuf descriptor of the field to convert
     */
    public ProtoPayload(Descriptors.FieldDescriptor fieldDescriptor) {
        this.fieldDescriptor = fieldDescriptor;
        this.parsedObject = null;
        this.level = 0;
    }

    /**
     * Creates a type-only payload for the given field at the specified nesting level.
     *
     * <p>The parsed value is set to {@code null}; the {@code level} records how deep the field sits
     * within the message tree.</p>
     *
     * @param fieldDescriptor the Protobuf descriptor of the field to convert
     * @param level the nesting depth of the field, where {@code 0} denotes the root level
     */
    public ProtoPayload(Descriptors.FieldDescriptor fieldDescriptor, int level) {
        this.fieldDescriptor = fieldDescriptor;
        this.parsedObject = null;
        this.level = level;
    }

    /**
     * Indicates whether the field represented by this payload sits at the root of the message tree.
     *
     * @return {@code true} if the nesting level is {@code 0}, {@code false} otherwise
     */
    public boolean isRootLevel() {
        return level == 0;
    }
}
