package com.gotocompany.depot.maxcompute.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.ArrayList;
import java.util.List;

/**
 * Mutable container that partitions a batch of {@link RecordWrapper} instances into those that are
 * valid (ready to be sent to MaxCompute) and those that are invalid (carrying an
 * {@link com.gotocompany.depot.error.ErrorInfo} and destined for error handling).
 *
 * <p>The sink builds one of these while converting an incoming batch: each source message is
 * decorated into a {@link RecordWrapper} and then routed into the valid or invalid list. Downstream,
 * the valid list drives the insert call and the invalid list feeds Depot's error reporting. The
 * all-arguments constructor and the list accessors are generated by Lombok. This class is not
 * thread-safe and is expected to be populated by a single thread.</p>
 *
 * @see RecordWrapper
 */
@AllArgsConstructor
@Getter
public class RecordWrappers {
    /**
     * Records that passed validation and are ready to be written to MaxCompute.
     */
    private List<RecordWrapper> validRecords;
    /**
     * Records that failed validation; each is expected to carry an
     * {@link com.gotocompany.depot.error.ErrorInfo} for downstream error handling.
     */
    private List<RecordWrapper> invalidRecords;

    /**
     * Creates an empty container with freshly allocated, empty valid and invalid record lists.
     *
     * <p>Use this constructor to start accumulating records via
     * {@link #addValidRecord(RecordWrapper)} and {@link #addInvalidRecord(RecordWrapper)}.</p>
     */
    public RecordWrappers() {
        this.validRecords = new ArrayList<>();
        this.invalidRecords = new ArrayList<>();
    }

    /**
     * Appends a successfully validated record to the valid-records list.
     *
     * @param recordWrapper the validated record to add
     */
    public void addValidRecord(RecordWrapper recordWrapper) {
        this.validRecords.add(recordWrapper);
    }

    /**
     * Appends a rejected record to the invalid-records list.
     *
     * @param recordWrapper the invalid record to add; expected to carry an
     *        {@link com.gotocompany.depot.error.ErrorInfo}
     */
    public void addInvalidRecord(RecordWrapper recordWrapper) {
        this.invalidRecords.add(recordWrapper);
    }

}
