package com.gotocompany.depot.maxcompute.model;

import com.aliyun.odps.PartitionSpec;
import com.aliyun.odps.data.Record;
import com.gotocompany.depot.error.ErrorInfo;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * Immutable wrapper that carries a single MaxCompute {@link Record} through the sink's processing
 * pipeline together with the bookkeeping the sink needs to track and route it.
 *
 * <p>Each wrapper bundles the record payload with its zero-based position in the incoming batch
 * ({@code index}), an optional {@link ErrorInfo} describing why the record was rejected (or
 * {@code null} when the record is valid), and the {@link PartitionSpec} that locates the record in
 * the destination table. Record decorators progressively populate the underlying record and then
 * emit a new wrapper, while the insert layer uses {@code index} to correlate per-row failures back
 * to the originating message. The all-arguments constructor and all accessors are generated by
 * Lombok.</p>
 *
 * @see com.gotocompany.depot.maxcompute.record.RecordDecorator
 * @see RecordWrappers
 */
@RequiredArgsConstructor
@Getter
public class RecordWrapper {
    /**
     * The MaxCompute row payload being assembled and ultimately written to the table.
     */
    private final Record record;
    /**
     * Zero-based position of this record within its originating batch, used to map per-row insert
     * outcomes back to the source message.
     */
    private final long index;
    /**
     * Details of the failure that invalidated this record, or {@code null} when the record is valid.
     */
    private final ErrorInfo errorInfo;
    /**
     * Partition the record belongs to in the destination table, or {@code null} when the table is
     * not partitioned or no partition has been resolved for the record.
     */
    private final PartitionSpec partitionSpec;
}
