package com.gotocompany.depot.redis.client;

import com.gotocompany.depot.config.RedisSinkConfig;
import com.gotocompany.depot.exception.ConfigurationException;
import com.gotocompany.depot.metrics.Instrumentation;
import com.gotocompany.depot.metrics.RedisSinkMetrics;
import com.gotocompany.depot.redis.client.response.RedisResponse;
import com.gotocompany.depot.redis.client.response.RedisStandaloneResponse;
import com.gotocompany.depot.redis.record.RedisRecord;
import com.gotocompany.depot.redis.ttl.RedisTTLFactory;
import com.gotocompany.depot.redis.ttl.RedisTtl;
import com.gotocompany.depot.redis.util.RedisSinkUtils;
import lombok.AllArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import redis.clients.jedis.DefaultJedisClientConfig;
import redis.clients.jedis.HostAndPort;
import redis.clients.jedis.Jedis;
import redis.clients.jedis.Pipeline;
import redis.clients.jedis.Response;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Redis standalone client.
 *
 * <p>This client writes an entire batch atomically: all record commands are queued on a Jedis
 * {@link Pipeline} wrapped in a {@code MULTI}/{@code EXEC} transaction, so either the whole batch is
 * applied or none of it is, which makes a failed batch safe to retry. Transient failures are handled
 * by recreating the Jedis connection and retrying up to a configurable number of times with a
 * back-off between attempts. Success, no-response and connection-retry counts are reported through
 * {@link RedisSinkMetrics}.</p>
 *
 * <p>The all-arguments constructor generated by Lombok is used mainly to inject collaborators
 * directly (for example in tests), whereas production code uses the
 * {@link #RedisStandaloneClient(Instrumentation, RedisSinkConfig)} constructor, which derives
 * everything from configuration. Like the underlying Jedis client, instances are not thread safe.</p>
 *
 * @see RedisClusterClient
 * @see RedisTtl
 */
@AllArgsConstructor
public class RedisStandaloneClient implements RedisClient {

    /**
     * Logging and metrics facade for the connection lifecycle and batch outcomes.
     */
    private final Instrumentation instrumentation;
    /**
     * Strategy that applies the configured time-to-live to each written key.
     */
    private final RedisTtl redisTTL;
    /**
     * Connection settings (timeouts and credentials) used when (re)creating the Jedis client.
     */
    private final DefaultJedisClientConfig defaultJedisClientConfig;
    /**
     * Address of the standalone Redis server this client connects to.
     */
    private final HostAndPort hostAndPort;
    /**
     * Active Jedis connection; created by {@link #init()} and recreated on retry.
     */
    private Jedis jedis;
    /**
     * Maximum number of additional attempts to recreate the connection and resend a failing batch.
     */
    private final int connectionMaxRetries;
    /**
     * Delay, in milliseconds, applied between connection retry attempts.
     */
    private final long connectionRetryBackoffMs;
    /**
     * Supplies the metric names captured for success, no-response and connection-retry events.
     */
    private final RedisSinkMetrics redisSinkMetrics;

    /**
     * Creates a standalone client by deriving all connection settings from configuration.
     *
     * <p>The connection retry policy, {@link RedisTtl} strategy (via {@link RedisTTLFactory}), Jedis
     * client configuration (via {@link RedisSinkUtils#getJedisConfig(RedisSinkConfig)}), target host
     * and port and {@link RedisSinkMetrics} are all resolved from the supplied configuration. The
     * actual Jedis connection is not opened until {@link #init()} is called.</p>
     *
     * @param instrumentation the instrumentation used for logging and metrics
     * @param config the Redis sink configuration
     * @throws ConfigurationException if the configured url cannot be parsed into a host and port
     */
    public RedisStandaloneClient(Instrumentation instrumentation, RedisSinkConfig config) {
        this.instrumentation = instrumentation;
        this.connectionMaxRetries = config.getSinkRedisConnectionMaxRetries();
        this.connectionRetryBackoffMs = config.getSinkRedisConnectionRetryBackoffMs();
        this.redisTTL = RedisTTLFactory.getTTl(config);
        this.defaultJedisClientConfig = RedisSinkUtils.getJedisConfig(config);
        this.hostAndPort = getHostPort(config);
        this.redisSinkMetrics = new RedisSinkMetrics(config);
    }

    /**
     * Parses the configured standalone url into a {@link HostAndPort}.
     *
     * @param config the configuration supplying {@link RedisSinkConfig#getSinkRedisUrls()}
     * @return the parsed host and port of the standalone server
     * @throws ConfigurationException if the configured url is not a valid {@code host:port} string
     */
    private static HostAndPort getHostPort(RedisSinkConfig config) {
        try {
            return HostAndPort.parseString(StringUtils.trim(config.getSinkRedisUrls()));
        } catch (IllegalArgumentException e) {
            throw new ConfigurationException(String.format("Invalid url for redis standalone: %s", config.getSinkRedisUrls()));
        }
    }

    /**
     * Pushes records in a transaction.
     * if the transaction fails, whole batch can be retried.
     *
     * <p>The batch is delegated to {@link #sendInternal(List)}, which wraps all commands in a
     * {@code MULTI}/{@code EXEC} transaction; if the transaction fails, the whole batch can safely be
     * retried. On a {@link RuntimeException} the client backs off for {@code connectionRetryBackoffMs}
     * milliseconds, recreates the Jedis connection via {@link #init()} and retries, up to
     * {@code connectionMaxRetries} additional attempts. When all retries are exhausted the no-response
     * metric is recorded and the exception is rethrown; a successful attempt records the success
     * metric.</p>
     *
     * @param records records to send
     * @return Custom response containing status of the API calls.
     * @throws RuntimeException if the batch could not be written after exhausting every attempt
     */


    @Override
    public List<RedisResponse> send(List<RedisRecord> records) {
        int retryCount = connectionMaxRetries;
        List<RedisResponse> redisResponseList = null;
        while (retryCount >= 0) {
            try {
                redisResponseList = sendInternal(records);
                instrumentSuccess(redisResponseList);
                break;
            } catch (RuntimeException e) {

                e.printStackTrace();
                if (retryCount == 0) {
                    instrumentFailure(records);
                    throw e;
                }
                instrumentation.logInfo("Backing off for " + connectionRetryBackoffMs + " milliseconds.");
                try {
                    Thread.sleep(connectionRetryBackoffMs);
                } catch (InterruptedException interruptedException) {
                    interruptedException.printStackTrace();
                }
                instrumentation.logInfo("Attempting to recreate Redis client. Retry attempt count : " + (connectionMaxRetries - retryCount + 1));
                instrumentConnectionRetry();
                this.init();

            }
            retryCount--;
        }
        return redisResponseList;
    }

    /**
     * Executes a single transactional attempt to write the batch on the current Jedis connection.
     *
     * <p>A {@link Pipeline} is opened and switched into transaction mode with {@code MULTI}. Each
     * record is sent through {@link RedisRecord#send(Pipeline, RedisTtl)}, which queues its write (and
     * optional TTL) command and yields a deferred {@link RedisStandaloneResponse}. The transaction is
     * committed with {@code EXEC} and the pipeline is synchronised, after which every deferred response
     * is resolved by {@link RedisStandaloneResponse#process()} into its final success or failure
     * form.</p>
     *
     * @param records the records to write in this transaction
     * @return the resolved {@link RedisResponse} for each record, in input order
     */
    public List<RedisResponse> sendInternal(List<RedisRecord> records) {
        Pipeline jedisPipelined = jedis.pipelined();
        jedisPipelined.multi();
        List<RedisStandaloneResponse> responses = records.stream()
                .map(redisRecord -> redisRecord.send(jedisPipelined, redisTTL))
                .collect(Collectors.toList());
        Response<List<Object>> executeResponse = jedisPipelined.exec();
        jedisPipelined.sync();
        instrumentation.logDebug("jedis responses: {}", executeResponse.get());
        return responses.stream().map(RedisStandaloneResponse::process).collect(Collectors.toList());
    }


    /**
     * Closes the underlying Jedis connection.
     *
     * <p>Logs the closure and releases the active {@link Jedis} connection. This override completes
     * normally and does not declare any checked exception.</p>
     */
    @Override
    public void close() {
        instrumentation.logInfo("Closing Jedis client");
        jedis.close();
    }

    /**
     * Opens a new Jedis connection to the configured standalone server.
     *
     * <p>Logs the target host and port and assigns a freshly created {@link Jedis} client, configured
     * with the resolved {@link DefaultJedisClientConfig}, to {@code jedis}. It is called once before
     * the first send and again during {@link #send(List)} to recover from a broken connection,
     * replacing any previously held connection reference.</p>
     */
    public void init() {
        instrumentation.logInfo("Initialising Jedis client: Host: {} Port: {}", hostAndPort.getHost(), hostAndPort.getPort());
        jedis = new Jedis(hostAndPort, defaultJedisClientConfig);
    }

    /**
     * Records the number of successful responses for a batch.
     *
     * @param redisResponseList the responses returned by a successful send attempt; its size is
     *     captured against {@link RedisSinkMetrics#getRedisSuccessResponseTotalMetric()}
     */
    private void instrumentSuccess(List<RedisResponse> redisResponseList) {
        long successCount = redisResponseList.size();
        instrumentation.captureCount(redisSinkMetrics.getRedisSuccessResponseTotalMetric(), successCount);
    }

    /**
     * Records that an entire batch failed to produce any response.
     *
     * @param validRecords the records that could not be written; its size is captured against
     *     {@link RedisSinkMetrics#getRedisNoResponseTotalMetric()}
     */
    private void instrumentFailure(List<RedisRecord> validRecords) {
        long failureCount = validRecords.size();
        instrumentation.captureCount(redisSinkMetrics.getRedisNoResponseTotalMetric(), failureCount);
    }

    /**
     * Records a single Redis connection-retry event against
     * {@link RedisSinkMetrics#getRedisConnectionRetryTotalMetric()}.
     */
    private void instrumentConnectionRetry() {
        instrumentation.captureCount(redisSinkMetrics.getRedisConnectionRetryTotalMetric(), 1L);
    }
}
