package com.gotocompany.depot.bigtable.parser;

import com.gotocompany.depot.common.Template;
import com.gotocompany.depot.message.ParsedMessage;
import lombok.AllArgsConstructor;

/**
 * Builds a Bigtable row key for a record by rendering a configured template against the parsed
 * message.
 *
 * <p>The row-key template is a Depot {@link Template} — a format pattern paired with the field names
 * that supply its arguments. For each record the parser extracts those field values from the
 * {@link ParsedMessage} and formats them into the final row-key string. The all-arguments constructor
 * is generated by Lombok's {@code @AllArgsConstructor}.</p>
 *
 * @see Template
 * @see com.gotocompany.depot.bigtable.parser.BigTableRecordParser
 */
@AllArgsConstructor
public class BigTableRowKeyParser {
    /** Template that defines the row-key pattern and the fields supplying its values. */
    private final Template keyTemplate;

    /**
     * Renders the row key for a parsed message from the configured template.
     *
     * @param parsedMessage the parsed message whose fields supply the template's values
     * @return the formatted row-key string
     */
    public String parse(ParsedMessage parsedMessage) {
        return keyTemplate.parse(parsedMessage);
    }
}
