package com.gotocompany.depot.maxcompute.schema;

import com.aliyun.odps.Column;
import com.aliyun.odps.TableSchema;
import com.google.protobuf.Descriptors;
import com.gotocompany.depot.config.MaxComputeSinkConfig;
import com.gotocompany.depot.maxcompute.converter.ProtobufConverterOrchestrator;
import com.gotocompany.depot.maxcompute.model.MaxComputeSchema;
import com.gotocompany.depot.maxcompute.model.ProtoPayload;
import com.gotocompany.depot.maxcompute.schema.partition.PartitioningStrategy;
import com.gotocompany.depot.maxcompute.util.MetadataUtil;
import lombok.RequiredArgsConstructor;
import org.apache.commons.lang3.StringUtils;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * Builds the {@link MaxComputeSchema} for the destination table from a Protobuf message descriptor.
 *
 * <p>The builder assembles the table's columns in three parts: metadata columns (driven by
 * configuration), data columns mapped from the Protobuf fields via the
 * {@link ProtobufConverterOrchestrator}, and, when partitioning is enabled, a partition column
 * supplied by the active {@link PartitioningStrategy}. Protobuf-to-MaxCompute type mapping is
 * delegated to the converter orchestrator, while metadata column typing is delegated to
 * {@link MetadataUtil}. The all-arguments constructor is generated by Lombok.</p>
 *
 * @see MaxComputeSchema
 * @see MaxComputeSchemaCache
 */
@RequiredArgsConstructor
public class MaxComputeSchemaBuilder {

    /**
     * Orchestrator that maps Protobuf field types to MaxCompute types for the data columns.
     */
    private final ProtobufConverterOrchestrator protobufConverterOrchestrator;
    /**
     * Sink configuration controlling partitioning, metadata columns, and the metadata namespace.
     */
    private final MaxComputeSinkConfig maxComputeSinkConfig;
    /**
     * Active partitioning strategy supplying the partition column, or {@code null} when partitioning is
     * disabled.
     */
    private final PartitioningStrategy partitioningStrategy;
    /**
     * Helper used to resolve MaxCompute types for metadata columns.
     */
    private final MetadataUtil metadataUtil;

    /**
     * Build MaxCompute schema from protobuf descriptor.
     * Converting the protobuf types in to MaxCompute types.
     *
     * <p>Metadata columns and data columns are assembled and added to the table schema; when
     * partitioning is enabled a partition column is also added. The returned schema bundles the
     * resulting {@link com.aliyun.odps.TableSchema} with a map of metadata column names to their
     * types.</p>
     *
     * @param descriptor Protobuf descriptor
     * @return MaxComputeSchema object encloses the TableSchema and metadata columns
     */
    public MaxComputeSchema build(Descriptors.Descriptor descriptor) {
        List<Column> metadataColumns = buildMetadataColumns();
        TableSchema.Builder tableSchemaBuilder = com.aliyun.odps.TableSchema.builder()
                .withColumns(metadataColumns)
                .withColumns(buildDataColumns(descriptor));
        Column partitionColumn = maxComputeSinkConfig.isTablePartitioningEnabled() ? buildPartitionColumn() : null;
        if (Objects.nonNull(partitionColumn)) {
            tableSchemaBuilder.withPartitionColumn(partitionColumn);
        }
        return new MaxComputeSchema(
                tableSchemaBuilder.build(),
                metadataColumns.stream().collect(Collectors.toMap(Column::getName, Column::getTypeInfo))
        );
    }

    /**
     * Maps the descriptor's fields to MaxCompute data columns.
     *
     * <p>Every field is mapped to a column whose type is resolved by the
     * {@link ProtobufConverterOrchestrator}, except the partition key field when partitioning is
     * enabled and the partitioning strategy replaces the original column (in which case the field is
     * represented solely by the partition column).</p>
     *
     * @param descriptor the Protobuf descriptor whose fields are mapped to columns
     * @return the list of data columns for the table schema
     */
    private List<Column> buildDataColumns(Descriptors.Descriptor descriptor) {
        return descriptor.getFields()
                .stream()
                .filter(fieldDescriptor -> {
                    if (!maxComputeSinkConfig.isTablePartitioningEnabled() || !fieldDescriptor.getName().equals(maxComputeSinkConfig.getTablePartitionKey())) {
                        return true;
                    }
                    return !partitioningStrategy.shouldReplaceOriginalColumn();
                })
                .map(fieldDescriptor -> Column.newBuilder(fieldDescriptor.getName(),
                                protobufConverterOrchestrator.toMaxComputeTypeInfo(new ProtoPayload(fieldDescriptor))).build())
                .collect(Collectors.toList());
    }

    /**
     * Returns the partition column supplied by the active partitioning strategy.
     *
     * @return the partition column definition
     */
    private Column buildPartitionColumn() {
        return partitioningStrategy.getPartitionColumn();
    }

    /**
     * Builds the metadata columns to prepend to the table schema, honouring the configured layout.
     *
     * <p>When metadata is disabled an empty list is returned. When no metadata namespace is configured
     * each metadata entry becomes its own column; otherwise all metadata is collapsed into a single
     * struct column named by the configured namespace. Column types are resolved via
     * {@link MetadataUtil}.</p>
     *
     * @return the list of metadata columns, which may be empty
     */
    private List<Column> buildMetadataColumns() {
        if (!maxComputeSinkConfig.shouldAddMetadata()) {
            return new ArrayList<>();
        }
        if (StringUtils.isBlank(maxComputeSinkConfig.getMaxcomputeMetadataNamespace())) {
            return maxComputeSinkConfig.getMetadataColumnsTypes()
                    .stream()
                    .map(tuple -> Column.newBuilder(tuple.getFirst(), metadataUtil.getMetadataTypeInfo(tuple.getSecond())).build())
                    .collect(Collectors.toList());
        }
        return Collections.singletonList(Column.newBuilder(maxComputeSinkConfig.getMaxcomputeMetadataNamespace(),
                metadataUtil.getMetadataTypeInfo(maxComputeSinkConfig.getMetadataColumnsTypes())).build());
    }

}
